data {
	int<lower=0> N;
	vector[N] dlogX;
	vector[N] growth_rate_Others;
	vector[N] fiber_response_Others;
	vector[N] pairwise_interaction_Others_Others;
	vector[N] pairwise_interaction_Others_Blautia;
	vector[N] pairwise_interaction_Others_Faecalibacterium;
	vector[N] pairwise_interaction_Others_Bifidobacterium;
	vector[N] pairwise_interaction_Others_Dorea;
	vector[N] pairwise_interaction_Others_Bacteroides;
	vector[N] pairwise_interaction_Others_Roseburia;
	vector[N] pairwise_interaction_Others_Eubacterium;
	vector[N] pairwise_interaction_Others_Prevotella;
	vector[N] pairwise_interaction_Others_Fusicatenibacter;
	vector[N] pairwise_interaction_Others_Anaerostipes;
	vector[N] pairwise_interaction_Others_Coprococcus;
	vector[N] pairwise_interaction_Others_Akkermansia;
	vector[N] pairwise_interaction_Others_Ruminococcus;
	vector[N] pairwise_interaction_Others_Collinsella;
	vector[N] pairwise_interaction_Others_Gemmiger;
	vector[N] pairwise_interaction_Others_Alistipes;
	vector[N] pairwise_interaction_Others_Clostridium;
	vector[N] pairwise_interaction_Others_Holdemanella;
	vector[N] pairwise_interaction_Others_Dialister;
	vector[N] growth_rate_Blautia;
	vector[N] fiber_response_Blautia;
	vector[N] pairwise_interaction_Blautia_Others;
	vector[N] pairwise_interaction_Blautia_Blautia;
	vector[N] pairwise_interaction_Blautia_Faecalibacterium;
	vector[N] pairwise_interaction_Blautia_Bifidobacterium;
	vector[N] pairwise_interaction_Blautia_Dorea;
	vector[N] pairwise_interaction_Blautia_Bacteroides;
	vector[N] pairwise_interaction_Blautia_Roseburia;
	vector[N] pairwise_interaction_Blautia_Eubacterium;
	vector[N] pairwise_interaction_Blautia_Prevotella;
	vector[N] pairwise_interaction_Blautia_Fusicatenibacter;
	vector[N] pairwise_interaction_Blautia_Anaerostipes;
	vector[N] pairwise_interaction_Blautia_Coprococcus;
	vector[N] pairwise_interaction_Blautia_Akkermansia;
	vector[N] pairwise_interaction_Blautia_Ruminococcus;
	vector[N] pairwise_interaction_Blautia_Collinsella;
	vector[N] pairwise_interaction_Blautia_Gemmiger;
	vector[N] pairwise_interaction_Blautia_Alistipes;
	vector[N] pairwise_interaction_Blautia_Clostridium;
	vector[N] pairwise_interaction_Blautia_Holdemanella;
	vector[N] pairwise_interaction_Blautia_Dialister;
	vector[N] growth_rate_Faecalibacterium;
	vector[N] fiber_response_Faecalibacterium;
	vector[N] pairwise_interaction_Faecalibacterium_Others;
	vector[N] pairwise_interaction_Faecalibacterium_Blautia;
	vector[N] pairwise_interaction_Faecalibacterium_Faecalibacterium;
	vector[N] pairwise_interaction_Faecalibacterium_Bifidobacterium;
	vector[N] pairwise_interaction_Faecalibacterium_Dorea;
	vector[N] pairwise_interaction_Faecalibacterium_Bacteroides;
	vector[N] pairwise_interaction_Faecalibacterium_Roseburia;
	vector[N] pairwise_interaction_Faecalibacterium_Eubacterium;
	vector[N] pairwise_interaction_Faecalibacterium_Prevotella;
	vector[N] pairwise_interaction_Faecalibacterium_Fusicatenibacter;
	vector[N] pairwise_interaction_Faecalibacterium_Anaerostipes;
	vector[N] pairwise_interaction_Faecalibacterium_Coprococcus;
	vector[N] pairwise_interaction_Faecalibacterium_Akkermansia;
	vector[N] pairwise_interaction_Faecalibacterium_Ruminococcus;
	vector[N] pairwise_interaction_Faecalibacterium_Collinsella;
	vector[N] pairwise_interaction_Faecalibacterium_Gemmiger;
	vector[N] pairwise_interaction_Faecalibacterium_Alistipes;
	vector[N] pairwise_interaction_Faecalibacterium_Clostridium;
	vector[N] pairwise_interaction_Faecalibacterium_Holdemanella;
	vector[N] pairwise_interaction_Faecalibacterium_Dialister;
	vector[N] growth_rate_Bifidobacterium;
	vector[N] fiber_response_Bifidobacterium;
	vector[N] pairwise_interaction_Bifidobacterium_Others;
	vector[N] pairwise_interaction_Bifidobacterium_Blautia;
	vector[N] pairwise_interaction_Bifidobacterium_Faecalibacterium;
	vector[N] pairwise_interaction_Bifidobacterium_Bifidobacterium;
	vector[N] pairwise_interaction_Bifidobacterium_Dorea;
	vector[N] pairwise_interaction_Bifidobacterium_Bacteroides;
	vector[N] pairwise_interaction_Bifidobacterium_Roseburia;
	vector[N] pairwise_interaction_Bifidobacterium_Eubacterium;
	vector[N] pairwise_interaction_Bifidobacterium_Prevotella;
	vector[N] pairwise_interaction_Bifidobacterium_Fusicatenibacter;
	vector[N] pairwise_interaction_Bifidobacterium_Anaerostipes;
	vector[N] pairwise_interaction_Bifidobacterium_Coprococcus;
	vector[N] pairwise_interaction_Bifidobacterium_Akkermansia;
	vector[N] pairwise_interaction_Bifidobacterium_Ruminococcus;
	vector[N] pairwise_interaction_Bifidobacterium_Collinsella;
	vector[N] pairwise_interaction_Bifidobacterium_Gemmiger;
	vector[N] pairwise_interaction_Bifidobacterium_Alistipes;
	vector[N] pairwise_interaction_Bifidobacterium_Clostridium;
	vector[N] pairwise_interaction_Bifidobacterium_Holdemanella;
	vector[N] pairwise_interaction_Bifidobacterium_Dialister;
	vector[N] growth_rate_Dorea;
	vector[N] fiber_response_Dorea;
	vector[N] pairwise_interaction_Dorea_Others;
	vector[N] pairwise_interaction_Dorea_Blautia;
	vector[N] pairwise_interaction_Dorea_Faecalibacterium;
	vector[N] pairwise_interaction_Dorea_Bifidobacterium;
	vector[N] pairwise_interaction_Dorea_Dorea;
	vector[N] pairwise_interaction_Dorea_Bacteroides;
	vector[N] pairwise_interaction_Dorea_Roseburia;
	vector[N] pairwise_interaction_Dorea_Eubacterium;
	vector[N] pairwise_interaction_Dorea_Prevotella;
	vector[N] pairwise_interaction_Dorea_Fusicatenibacter;
	vector[N] pairwise_interaction_Dorea_Anaerostipes;
	vector[N] pairwise_interaction_Dorea_Coprococcus;
	vector[N] pairwise_interaction_Dorea_Akkermansia;
	vector[N] pairwise_interaction_Dorea_Ruminococcus;
	vector[N] pairwise_interaction_Dorea_Collinsella;
	vector[N] pairwise_interaction_Dorea_Gemmiger;
	vector[N] pairwise_interaction_Dorea_Alistipes;
	vector[N] pairwise_interaction_Dorea_Clostridium;
	vector[N] pairwise_interaction_Dorea_Holdemanella;
	vector[N] pairwise_interaction_Dorea_Dialister;
	vector[N] growth_rate_Bacteroides;
	vector[N] fiber_response_Bacteroides;
	vector[N] pairwise_interaction_Bacteroides_Others;
	vector[N] pairwise_interaction_Bacteroides_Blautia;
	vector[N] pairwise_interaction_Bacteroides_Faecalibacterium;
	vector[N] pairwise_interaction_Bacteroides_Bifidobacterium;
	vector[N] pairwise_interaction_Bacteroides_Dorea;
	vector[N] pairwise_interaction_Bacteroides_Bacteroides;
	vector[N] pairwise_interaction_Bacteroides_Roseburia;
	vector[N] pairwise_interaction_Bacteroides_Eubacterium;
	vector[N] pairwise_interaction_Bacteroides_Prevotella;
	vector[N] pairwise_interaction_Bacteroides_Fusicatenibacter;
	vector[N] pairwise_interaction_Bacteroides_Anaerostipes;
	vector[N] pairwise_interaction_Bacteroides_Coprococcus;
	vector[N] pairwise_interaction_Bacteroides_Akkermansia;
	vector[N] pairwise_interaction_Bacteroides_Ruminococcus;
	vector[N] pairwise_interaction_Bacteroides_Collinsella;
	vector[N] pairwise_interaction_Bacteroides_Gemmiger;
	vector[N] pairwise_interaction_Bacteroides_Alistipes;
	vector[N] pairwise_interaction_Bacteroides_Clostridium;
	vector[N] pairwise_interaction_Bacteroides_Holdemanella;
	vector[N] pairwise_interaction_Bacteroides_Dialister;
	vector[N] growth_rate_Roseburia;
	vector[N] fiber_response_Roseburia;
	vector[N] pairwise_interaction_Roseburia_Others;
	vector[N] pairwise_interaction_Roseburia_Blautia;
	vector[N] pairwise_interaction_Roseburia_Faecalibacterium;
	vector[N] pairwise_interaction_Roseburia_Bifidobacterium;
	vector[N] pairwise_interaction_Roseburia_Dorea;
	vector[N] pairwise_interaction_Roseburia_Bacteroides;
	vector[N] pairwise_interaction_Roseburia_Roseburia;
	vector[N] pairwise_interaction_Roseburia_Eubacterium;
	vector[N] pairwise_interaction_Roseburia_Prevotella;
	vector[N] pairwise_interaction_Roseburia_Fusicatenibacter;
	vector[N] pairwise_interaction_Roseburia_Anaerostipes;
	vector[N] pairwise_interaction_Roseburia_Coprococcus;
	vector[N] pairwise_interaction_Roseburia_Akkermansia;
	vector[N] pairwise_interaction_Roseburia_Ruminococcus;
	vector[N] pairwise_interaction_Roseburia_Collinsella;
	vector[N] pairwise_interaction_Roseburia_Gemmiger;
	vector[N] pairwise_interaction_Roseburia_Alistipes;
	vector[N] pairwise_interaction_Roseburia_Clostridium;
	vector[N] pairwise_interaction_Roseburia_Holdemanella;
	vector[N] pairwise_interaction_Roseburia_Dialister;
	vector[N] growth_rate_Eubacterium;
	vector[N] fiber_response_Eubacterium;
	vector[N] pairwise_interaction_Eubacterium_Others;
	vector[N] pairwise_interaction_Eubacterium_Blautia;
	vector[N] pairwise_interaction_Eubacterium_Faecalibacterium;
	vector[N] pairwise_interaction_Eubacterium_Bifidobacterium;
	vector[N] pairwise_interaction_Eubacterium_Dorea;
	vector[N] pairwise_interaction_Eubacterium_Bacteroides;
	vector[N] pairwise_interaction_Eubacterium_Roseburia;
	vector[N] pairwise_interaction_Eubacterium_Eubacterium;
	vector[N] pairwise_interaction_Eubacterium_Prevotella;
	vector[N] pairwise_interaction_Eubacterium_Fusicatenibacter;
	vector[N] pairwise_interaction_Eubacterium_Anaerostipes;
	vector[N] pairwise_interaction_Eubacterium_Coprococcus;
	vector[N] pairwise_interaction_Eubacterium_Akkermansia;
	vector[N] pairwise_interaction_Eubacterium_Ruminococcus;
	vector[N] pairwise_interaction_Eubacterium_Collinsella;
	vector[N] pairwise_interaction_Eubacterium_Gemmiger;
	vector[N] pairwise_interaction_Eubacterium_Alistipes;
	vector[N] pairwise_interaction_Eubacterium_Clostridium;
	vector[N] pairwise_interaction_Eubacterium_Holdemanella;
	vector[N] pairwise_interaction_Eubacterium_Dialister;
	vector[N] growth_rate_Prevotella;
	vector[N] fiber_response_Prevotella;
	vector[N] pairwise_interaction_Prevotella_Others;
	vector[N] pairwise_interaction_Prevotella_Blautia;
	vector[N] pairwise_interaction_Prevotella_Faecalibacterium;
	vector[N] pairwise_interaction_Prevotella_Bifidobacterium;
	vector[N] pairwise_interaction_Prevotella_Dorea;
	vector[N] pairwise_interaction_Prevotella_Bacteroides;
	vector[N] pairwise_interaction_Prevotella_Roseburia;
	vector[N] pairwise_interaction_Prevotella_Eubacterium;
	vector[N] pairwise_interaction_Prevotella_Prevotella;
	vector[N] pairwise_interaction_Prevotella_Fusicatenibacter;
	vector[N] pairwise_interaction_Prevotella_Anaerostipes;
	vector[N] pairwise_interaction_Prevotella_Coprococcus;
	vector[N] pairwise_interaction_Prevotella_Akkermansia;
	vector[N] pairwise_interaction_Prevotella_Ruminococcus;
	vector[N] pairwise_interaction_Prevotella_Collinsella;
	vector[N] pairwise_interaction_Prevotella_Gemmiger;
	vector[N] pairwise_interaction_Prevotella_Alistipes;
	vector[N] pairwise_interaction_Prevotella_Clostridium;
	vector[N] pairwise_interaction_Prevotella_Holdemanella;
	vector[N] pairwise_interaction_Prevotella_Dialister;
	vector[N] growth_rate_Fusicatenibacter;
	vector[N] fiber_response_Fusicatenibacter;
	vector[N] pairwise_interaction_Fusicatenibacter_Others;
	vector[N] pairwise_interaction_Fusicatenibacter_Blautia;
	vector[N] pairwise_interaction_Fusicatenibacter_Faecalibacterium;
	vector[N] pairwise_interaction_Fusicatenibacter_Bifidobacterium;
	vector[N] pairwise_interaction_Fusicatenibacter_Dorea;
	vector[N] pairwise_interaction_Fusicatenibacter_Bacteroides;
	vector[N] pairwise_interaction_Fusicatenibacter_Roseburia;
	vector[N] pairwise_interaction_Fusicatenibacter_Eubacterium;
	vector[N] pairwise_interaction_Fusicatenibacter_Prevotella;
	vector[N] pairwise_interaction_Fusicatenibacter_Fusicatenibacter;
	vector[N] pairwise_interaction_Fusicatenibacter_Anaerostipes;
	vector[N] pairwise_interaction_Fusicatenibacter_Coprococcus;
	vector[N] pairwise_interaction_Fusicatenibacter_Akkermansia;
	vector[N] pairwise_interaction_Fusicatenibacter_Ruminococcus;
	vector[N] pairwise_interaction_Fusicatenibacter_Collinsella;
	vector[N] pairwise_interaction_Fusicatenibacter_Gemmiger;
	vector[N] pairwise_interaction_Fusicatenibacter_Alistipes;
	vector[N] pairwise_interaction_Fusicatenibacter_Clostridium;
	vector[N] pairwise_interaction_Fusicatenibacter_Holdemanella;
	vector[N] pairwise_interaction_Fusicatenibacter_Dialister;
	vector[N] growth_rate_Anaerostipes;
	vector[N] fiber_response_Anaerostipes;
	vector[N] pairwise_interaction_Anaerostipes_Others;
	vector[N] pairwise_interaction_Anaerostipes_Blautia;
	vector[N] pairwise_interaction_Anaerostipes_Faecalibacterium;
	vector[N] pairwise_interaction_Anaerostipes_Bifidobacterium;
	vector[N] pairwise_interaction_Anaerostipes_Dorea;
	vector[N] pairwise_interaction_Anaerostipes_Bacteroides;
	vector[N] pairwise_interaction_Anaerostipes_Roseburia;
	vector[N] pairwise_interaction_Anaerostipes_Eubacterium;
	vector[N] pairwise_interaction_Anaerostipes_Prevotella;
	vector[N] pairwise_interaction_Anaerostipes_Fusicatenibacter;
	vector[N] pairwise_interaction_Anaerostipes_Anaerostipes;
	vector[N] pairwise_interaction_Anaerostipes_Coprococcus;
	vector[N] pairwise_interaction_Anaerostipes_Akkermansia;
	vector[N] pairwise_interaction_Anaerostipes_Ruminococcus;
	vector[N] pairwise_interaction_Anaerostipes_Collinsella;
	vector[N] pairwise_interaction_Anaerostipes_Gemmiger;
	vector[N] pairwise_interaction_Anaerostipes_Alistipes;
	vector[N] pairwise_interaction_Anaerostipes_Clostridium;
	vector[N] pairwise_interaction_Anaerostipes_Holdemanella;
	vector[N] pairwise_interaction_Anaerostipes_Dialister;
	vector[N] growth_rate_Coprococcus;
	vector[N] fiber_response_Coprococcus;
	vector[N] pairwise_interaction_Coprococcus_Others;
	vector[N] pairwise_interaction_Coprococcus_Blautia;
	vector[N] pairwise_interaction_Coprococcus_Faecalibacterium;
	vector[N] pairwise_interaction_Coprococcus_Bifidobacterium;
	vector[N] pairwise_interaction_Coprococcus_Dorea;
	vector[N] pairwise_interaction_Coprococcus_Bacteroides;
	vector[N] pairwise_interaction_Coprococcus_Roseburia;
	vector[N] pairwise_interaction_Coprococcus_Eubacterium;
	vector[N] pairwise_interaction_Coprococcus_Prevotella;
	vector[N] pairwise_interaction_Coprococcus_Fusicatenibacter;
	vector[N] pairwise_interaction_Coprococcus_Anaerostipes;
	vector[N] pairwise_interaction_Coprococcus_Coprococcus;
	vector[N] pairwise_interaction_Coprococcus_Akkermansia;
	vector[N] pairwise_interaction_Coprococcus_Ruminococcus;
	vector[N] pairwise_interaction_Coprococcus_Collinsella;
	vector[N] pairwise_interaction_Coprococcus_Gemmiger;
	vector[N] pairwise_interaction_Coprococcus_Alistipes;
	vector[N] pairwise_interaction_Coprococcus_Clostridium;
	vector[N] pairwise_interaction_Coprococcus_Holdemanella;
	vector[N] pairwise_interaction_Coprococcus_Dialister;
	vector[N] growth_rate_Akkermansia;
	vector[N] fiber_response_Akkermansia;
	vector[N] pairwise_interaction_Akkermansia_Others;
	vector[N] pairwise_interaction_Akkermansia_Blautia;
	vector[N] pairwise_interaction_Akkermansia_Faecalibacterium;
	vector[N] pairwise_interaction_Akkermansia_Bifidobacterium;
	vector[N] pairwise_interaction_Akkermansia_Dorea;
	vector[N] pairwise_interaction_Akkermansia_Bacteroides;
	vector[N] pairwise_interaction_Akkermansia_Roseburia;
	vector[N] pairwise_interaction_Akkermansia_Eubacterium;
	vector[N] pairwise_interaction_Akkermansia_Prevotella;
	vector[N] pairwise_interaction_Akkermansia_Fusicatenibacter;
	vector[N] pairwise_interaction_Akkermansia_Anaerostipes;
	vector[N] pairwise_interaction_Akkermansia_Coprococcus;
	vector[N] pairwise_interaction_Akkermansia_Akkermansia;
	vector[N] pairwise_interaction_Akkermansia_Ruminococcus;
	vector[N] pairwise_interaction_Akkermansia_Collinsella;
	vector[N] pairwise_interaction_Akkermansia_Gemmiger;
	vector[N] pairwise_interaction_Akkermansia_Alistipes;
	vector[N] pairwise_interaction_Akkermansia_Clostridium;
	vector[N] pairwise_interaction_Akkermansia_Holdemanella;
	vector[N] pairwise_interaction_Akkermansia_Dialister;
	vector[N] growth_rate_Ruminococcus;
	vector[N] fiber_response_Ruminococcus;
	vector[N] pairwise_interaction_Ruminococcus_Others;
	vector[N] pairwise_interaction_Ruminococcus_Blautia;
	vector[N] pairwise_interaction_Ruminococcus_Faecalibacterium;
	vector[N] pairwise_interaction_Ruminococcus_Bifidobacterium;
	vector[N] pairwise_interaction_Ruminococcus_Dorea;
	vector[N] pairwise_interaction_Ruminococcus_Bacteroides;
	vector[N] pairwise_interaction_Ruminococcus_Roseburia;
	vector[N] pairwise_interaction_Ruminococcus_Eubacterium;
	vector[N] pairwise_interaction_Ruminococcus_Prevotella;
	vector[N] pairwise_interaction_Ruminococcus_Fusicatenibacter;
	vector[N] pairwise_interaction_Ruminococcus_Anaerostipes;
	vector[N] pairwise_interaction_Ruminococcus_Coprococcus;
	vector[N] pairwise_interaction_Ruminococcus_Akkermansia;
	vector[N] pairwise_interaction_Ruminococcus_Ruminococcus;
	vector[N] pairwise_interaction_Ruminococcus_Collinsella;
	vector[N] pairwise_interaction_Ruminococcus_Gemmiger;
	vector[N] pairwise_interaction_Ruminococcus_Alistipes;
	vector[N] pairwise_interaction_Ruminococcus_Clostridium;
	vector[N] pairwise_interaction_Ruminococcus_Holdemanella;
	vector[N] pairwise_interaction_Ruminococcus_Dialister;
	vector[N] growth_rate_Collinsella;
	vector[N] fiber_response_Collinsella;
	vector[N] pairwise_interaction_Collinsella_Others;
	vector[N] pairwise_interaction_Collinsella_Blautia;
	vector[N] pairwise_interaction_Collinsella_Faecalibacterium;
	vector[N] pairwise_interaction_Collinsella_Bifidobacterium;
	vector[N] pairwise_interaction_Collinsella_Dorea;
	vector[N] pairwise_interaction_Collinsella_Bacteroides;
	vector[N] pairwise_interaction_Collinsella_Roseburia;
	vector[N] pairwise_interaction_Collinsella_Eubacterium;
	vector[N] pairwise_interaction_Collinsella_Prevotella;
	vector[N] pairwise_interaction_Collinsella_Fusicatenibacter;
	vector[N] pairwise_interaction_Collinsella_Anaerostipes;
	vector[N] pairwise_interaction_Collinsella_Coprococcus;
	vector[N] pairwise_interaction_Collinsella_Akkermansia;
	vector[N] pairwise_interaction_Collinsella_Ruminococcus;
	vector[N] pairwise_interaction_Collinsella_Collinsella;
	vector[N] pairwise_interaction_Collinsella_Gemmiger;
	vector[N] pairwise_interaction_Collinsella_Alistipes;
	vector[N] pairwise_interaction_Collinsella_Clostridium;
	vector[N] pairwise_interaction_Collinsella_Holdemanella;
	vector[N] pairwise_interaction_Collinsella_Dialister;
	vector[N] growth_rate_Gemmiger;
	vector[N] fiber_response_Gemmiger;
	vector[N] pairwise_interaction_Gemmiger_Others;
	vector[N] pairwise_interaction_Gemmiger_Blautia;
	vector[N] pairwise_interaction_Gemmiger_Faecalibacterium;
	vector[N] pairwise_interaction_Gemmiger_Bifidobacterium;
	vector[N] pairwise_interaction_Gemmiger_Dorea;
	vector[N] pairwise_interaction_Gemmiger_Bacteroides;
	vector[N] pairwise_interaction_Gemmiger_Roseburia;
	vector[N] pairwise_interaction_Gemmiger_Eubacterium;
	vector[N] pairwise_interaction_Gemmiger_Prevotella;
	vector[N] pairwise_interaction_Gemmiger_Fusicatenibacter;
	vector[N] pairwise_interaction_Gemmiger_Anaerostipes;
	vector[N] pairwise_interaction_Gemmiger_Coprococcus;
	vector[N] pairwise_interaction_Gemmiger_Akkermansia;
	vector[N] pairwise_interaction_Gemmiger_Ruminococcus;
	vector[N] pairwise_interaction_Gemmiger_Collinsella;
	vector[N] pairwise_interaction_Gemmiger_Gemmiger;
	vector[N] pairwise_interaction_Gemmiger_Alistipes;
	vector[N] pairwise_interaction_Gemmiger_Clostridium;
	vector[N] pairwise_interaction_Gemmiger_Holdemanella;
	vector[N] pairwise_interaction_Gemmiger_Dialister;
	vector[N] growth_rate_Alistipes;
	vector[N] fiber_response_Alistipes;
	vector[N] pairwise_interaction_Alistipes_Others;
	vector[N] pairwise_interaction_Alistipes_Blautia;
	vector[N] pairwise_interaction_Alistipes_Faecalibacterium;
	vector[N] pairwise_interaction_Alistipes_Bifidobacterium;
	vector[N] pairwise_interaction_Alistipes_Dorea;
	vector[N] pairwise_interaction_Alistipes_Bacteroides;
	vector[N] pairwise_interaction_Alistipes_Roseburia;
	vector[N] pairwise_interaction_Alistipes_Eubacterium;
	vector[N] pairwise_interaction_Alistipes_Prevotella;
	vector[N] pairwise_interaction_Alistipes_Fusicatenibacter;
	vector[N] pairwise_interaction_Alistipes_Anaerostipes;
	vector[N] pairwise_interaction_Alistipes_Coprococcus;
	vector[N] pairwise_interaction_Alistipes_Akkermansia;
	vector[N] pairwise_interaction_Alistipes_Ruminococcus;
	vector[N] pairwise_interaction_Alistipes_Collinsella;
	vector[N] pairwise_interaction_Alistipes_Gemmiger;
	vector[N] pairwise_interaction_Alistipes_Alistipes;
	vector[N] pairwise_interaction_Alistipes_Clostridium;
	vector[N] pairwise_interaction_Alistipes_Holdemanella;
	vector[N] pairwise_interaction_Alistipes_Dialister;
	vector[N] growth_rate_Clostridium;
	vector[N] fiber_response_Clostridium;
	vector[N] pairwise_interaction_Clostridium_Others;
	vector[N] pairwise_interaction_Clostridium_Blautia;
	vector[N] pairwise_interaction_Clostridium_Faecalibacterium;
	vector[N] pairwise_interaction_Clostridium_Bifidobacterium;
	vector[N] pairwise_interaction_Clostridium_Dorea;
	vector[N] pairwise_interaction_Clostridium_Bacteroides;
	vector[N] pairwise_interaction_Clostridium_Roseburia;
	vector[N] pairwise_interaction_Clostridium_Eubacterium;
	vector[N] pairwise_interaction_Clostridium_Prevotella;
	vector[N] pairwise_interaction_Clostridium_Fusicatenibacter;
	vector[N] pairwise_interaction_Clostridium_Anaerostipes;
	vector[N] pairwise_interaction_Clostridium_Coprococcus;
	vector[N] pairwise_interaction_Clostridium_Akkermansia;
	vector[N] pairwise_interaction_Clostridium_Ruminococcus;
	vector[N] pairwise_interaction_Clostridium_Collinsella;
	vector[N] pairwise_interaction_Clostridium_Gemmiger;
	vector[N] pairwise_interaction_Clostridium_Alistipes;
	vector[N] pairwise_interaction_Clostridium_Clostridium;
	vector[N] pairwise_interaction_Clostridium_Holdemanella;
	vector[N] pairwise_interaction_Clostridium_Dialister;
	vector[N] growth_rate_Holdemanella;
	vector[N] fiber_response_Holdemanella;
	vector[N] pairwise_interaction_Holdemanella_Others;
	vector[N] pairwise_interaction_Holdemanella_Blautia;
	vector[N] pairwise_interaction_Holdemanella_Faecalibacterium;
	vector[N] pairwise_interaction_Holdemanella_Bifidobacterium;
	vector[N] pairwise_interaction_Holdemanella_Dorea;
	vector[N] pairwise_interaction_Holdemanella_Bacteroides;
	vector[N] pairwise_interaction_Holdemanella_Roseburia;
	vector[N] pairwise_interaction_Holdemanella_Eubacterium;
	vector[N] pairwise_interaction_Holdemanella_Prevotella;
	vector[N] pairwise_interaction_Holdemanella_Fusicatenibacter;
	vector[N] pairwise_interaction_Holdemanella_Anaerostipes;
	vector[N] pairwise_interaction_Holdemanella_Coprococcus;
	vector[N] pairwise_interaction_Holdemanella_Akkermansia;
	vector[N] pairwise_interaction_Holdemanella_Ruminococcus;
	vector[N] pairwise_interaction_Holdemanella_Collinsella;
	vector[N] pairwise_interaction_Holdemanella_Gemmiger;
	vector[N] pairwise_interaction_Holdemanella_Alistipes;
	vector[N] pairwise_interaction_Holdemanella_Clostridium;
	vector[N] pairwise_interaction_Holdemanella_Holdemanella;
	vector[N] pairwise_interaction_Holdemanella_Dialister;
	vector[N] growth_rate_Dialister;
	vector[N] fiber_response_Dialister;
	vector[N] pairwise_interaction_Dialister_Others;
	vector[N] pairwise_interaction_Dialister_Blautia;
	vector[N] pairwise_interaction_Dialister_Faecalibacterium;
	vector[N] pairwise_interaction_Dialister_Bifidobacterium;
	vector[N] pairwise_interaction_Dialister_Dorea;
	vector[N] pairwise_interaction_Dialister_Bacteroides;
	vector[N] pairwise_interaction_Dialister_Roseburia;
	vector[N] pairwise_interaction_Dialister_Eubacterium;
	vector[N] pairwise_interaction_Dialister_Prevotella;
	vector[N] pairwise_interaction_Dialister_Fusicatenibacter;
	vector[N] pairwise_interaction_Dialister_Anaerostipes;
	vector[N] pairwise_interaction_Dialister_Coprococcus;
	vector[N] pairwise_interaction_Dialister_Akkermansia;
	vector[N] pairwise_interaction_Dialister_Ruminococcus;
	vector[N] pairwise_interaction_Dialister_Collinsella;
	vector[N] pairwise_interaction_Dialister_Gemmiger;
	vector[N] pairwise_interaction_Dialister_Alistipes;
	vector[N] pairwise_interaction_Dialister_Clostridium;
	vector[N] pairwise_interaction_Dialister_Holdemanella;
	vector[N] pairwise_interaction_Dialister_Dialister;
}
parameters {
	real<lower=0,upper=1> sigma;
	real alpha__Others;
	real epsilon__Others;
	real beta__Others_Others;
	real beta__Others_Blautia;
	real beta__Others_Faecalibacterium;
	real beta__Others_Bifidobacterium;
	real beta__Others_Dorea;
	real beta__Others_Bacteroides;
	real beta__Others_Roseburia;
	real beta__Others_Eubacterium;
	real beta__Others_Prevotella;
	real beta__Others_Fusicatenibacter;
	real beta__Others_Anaerostipes;
	real beta__Others_Coprococcus;
	real beta__Others_Akkermansia;
	real beta__Others_Ruminococcus;
	real beta__Others_Collinsella;
	real beta__Others_Gemmiger;
	real beta__Others_Alistipes;
	real beta__Others_Clostridium;
	real beta__Others_Holdemanella;
	real beta__Others_Dialister;
	real alpha__Blautia;
	real epsilon__Blautia;
	real beta__Blautia_Others;
	real beta__Blautia_Blautia;
	real beta__Blautia_Faecalibacterium;
	real beta__Blautia_Bifidobacterium;
	real beta__Blautia_Dorea;
	real beta__Blautia_Bacteroides;
	real beta__Blautia_Roseburia;
	real beta__Blautia_Eubacterium;
	real beta__Blautia_Prevotella;
	real beta__Blautia_Fusicatenibacter;
	real beta__Blautia_Anaerostipes;
	real beta__Blautia_Coprococcus;
	real beta__Blautia_Akkermansia;
	real beta__Blautia_Ruminococcus;
	real beta__Blautia_Collinsella;
	real beta__Blautia_Gemmiger;
	real beta__Blautia_Alistipes;
	real beta__Blautia_Clostridium;
	real beta__Blautia_Holdemanella;
	real beta__Blautia_Dialister;
	real alpha__Faecalibacterium;
	real epsilon__Faecalibacterium;
	real beta__Faecalibacterium_Others;
	real beta__Faecalibacterium_Blautia;
	real beta__Faecalibacterium_Faecalibacterium;
	real beta__Faecalibacterium_Bifidobacterium;
	real beta__Faecalibacterium_Dorea;
	real beta__Faecalibacterium_Bacteroides;
	real beta__Faecalibacterium_Roseburia;
	real beta__Faecalibacterium_Eubacterium;
	real beta__Faecalibacterium_Prevotella;
	real beta__Faecalibacterium_Fusicatenibacter;
	real beta__Faecalibacterium_Anaerostipes;
	real beta__Faecalibacterium_Coprococcus;
	real beta__Faecalibacterium_Akkermansia;
	real beta__Faecalibacterium_Ruminococcus;
	real beta__Faecalibacterium_Collinsella;
	real beta__Faecalibacterium_Gemmiger;
	real beta__Faecalibacterium_Alistipes;
	real beta__Faecalibacterium_Clostridium;
	real beta__Faecalibacterium_Holdemanella;
	real beta__Faecalibacterium_Dialister;
	real alpha__Bifidobacterium;
	real epsilon__Bifidobacterium;
	real beta__Bifidobacterium_Others;
	real beta__Bifidobacterium_Blautia;
	real beta__Bifidobacterium_Faecalibacterium;
	real beta__Bifidobacterium_Bifidobacterium;
	real beta__Bifidobacterium_Dorea;
	real beta__Bifidobacterium_Bacteroides;
	real beta__Bifidobacterium_Roseburia;
	real beta__Bifidobacterium_Eubacterium;
	real beta__Bifidobacterium_Prevotella;
	real beta__Bifidobacterium_Fusicatenibacter;
	real beta__Bifidobacterium_Anaerostipes;
	real beta__Bifidobacterium_Coprococcus;
	real beta__Bifidobacterium_Akkermansia;
	real beta__Bifidobacterium_Ruminococcus;
	real beta__Bifidobacterium_Collinsella;
	real beta__Bifidobacterium_Gemmiger;
	real beta__Bifidobacterium_Alistipes;
	real beta__Bifidobacterium_Clostridium;
	real beta__Bifidobacterium_Holdemanella;
	real beta__Bifidobacterium_Dialister;
	real alpha__Dorea;
	real epsilon__Dorea;
	real beta__Dorea_Others;
	real beta__Dorea_Blautia;
	real beta__Dorea_Faecalibacterium;
	real beta__Dorea_Bifidobacterium;
	real beta__Dorea_Dorea;
	real beta__Dorea_Bacteroides;
	real beta__Dorea_Roseburia;
	real beta__Dorea_Eubacterium;
	real beta__Dorea_Prevotella;
	real beta__Dorea_Fusicatenibacter;
	real beta__Dorea_Anaerostipes;
	real beta__Dorea_Coprococcus;
	real beta__Dorea_Akkermansia;
	real beta__Dorea_Ruminococcus;
	real beta__Dorea_Collinsella;
	real beta__Dorea_Gemmiger;
	real beta__Dorea_Alistipes;
	real beta__Dorea_Clostridium;
	real beta__Dorea_Holdemanella;
	real beta__Dorea_Dialister;
	real alpha__Bacteroides;
	real epsilon__Bacteroides;
	real beta__Bacteroides_Others;
	real beta__Bacteroides_Blautia;
	real beta__Bacteroides_Faecalibacterium;
	real beta__Bacteroides_Bifidobacterium;
	real beta__Bacteroides_Dorea;
	real beta__Bacteroides_Bacteroides;
	real beta__Bacteroides_Roseburia;
	real beta__Bacteroides_Eubacterium;
	real beta__Bacteroides_Prevotella;
	real beta__Bacteroides_Fusicatenibacter;
	real beta__Bacteroides_Anaerostipes;
	real beta__Bacteroides_Coprococcus;
	real beta__Bacteroides_Akkermansia;
	real beta__Bacteroides_Ruminococcus;
	real beta__Bacteroides_Collinsella;
	real beta__Bacteroides_Gemmiger;
	real beta__Bacteroides_Alistipes;
	real beta__Bacteroides_Clostridium;
	real beta__Bacteroides_Holdemanella;
	real beta__Bacteroides_Dialister;
	real alpha__Roseburia;
	real epsilon__Roseburia;
	real beta__Roseburia_Others;
	real beta__Roseburia_Blautia;
	real beta__Roseburia_Faecalibacterium;
	real beta__Roseburia_Bifidobacterium;
	real beta__Roseburia_Dorea;
	real beta__Roseburia_Bacteroides;
	real beta__Roseburia_Roseburia;
	real beta__Roseburia_Eubacterium;
	real beta__Roseburia_Prevotella;
	real beta__Roseburia_Fusicatenibacter;
	real beta__Roseburia_Anaerostipes;
	real beta__Roseburia_Coprococcus;
	real beta__Roseburia_Akkermansia;
	real beta__Roseburia_Ruminococcus;
	real beta__Roseburia_Collinsella;
	real beta__Roseburia_Gemmiger;
	real beta__Roseburia_Alistipes;
	real beta__Roseburia_Clostridium;
	real beta__Roseburia_Holdemanella;
	real beta__Roseburia_Dialister;
	real alpha__Eubacterium;
	real epsilon__Eubacterium;
	real beta__Eubacterium_Others;
	real beta__Eubacterium_Blautia;
	real beta__Eubacterium_Faecalibacterium;
	real beta__Eubacterium_Bifidobacterium;
	real beta__Eubacterium_Dorea;
	real beta__Eubacterium_Bacteroides;
	real beta__Eubacterium_Roseburia;
	real beta__Eubacterium_Eubacterium;
	real beta__Eubacterium_Prevotella;
	real beta__Eubacterium_Fusicatenibacter;
	real beta__Eubacterium_Anaerostipes;
	real beta__Eubacterium_Coprococcus;
	real beta__Eubacterium_Akkermansia;
	real beta__Eubacterium_Ruminococcus;
	real beta__Eubacterium_Collinsella;
	real beta__Eubacterium_Gemmiger;
	real beta__Eubacterium_Alistipes;
	real beta__Eubacterium_Clostridium;
	real beta__Eubacterium_Holdemanella;
	real beta__Eubacterium_Dialister;
	real alpha__Prevotella;
	real epsilon__Prevotella;
	real beta__Prevotella_Others;
	real beta__Prevotella_Blautia;
	real beta__Prevotella_Faecalibacterium;
	real beta__Prevotella_Bifidobacterium;
	real beta__Prevotella_Dorea;
	real beta__Prevotella_Bacteroides;
	real beta__Prevotella_Roseburia;
	real beta__Prevotella_Eubacterium;
	real beta__Prevotella_Prevotella;
	real beta__Prevotella_Fusicatenibacter;
	real beta__Prevotella_Anaerostipes;
	real beta__Prevotella_Coprococcus;
	real beta__Prevotella_Akkermansia;
	real beta__Prevotella_Ruminococcus;
	real beta__Prevotella_Collinsella;
	real beta__Prevotella_Gemmiger;
	real beta__Prevotella_Alistipes;
	real beta__Prevotella_Clostridium;
	real beta__Prevotella_Holdemanella;
	real beta__Prevotella_Dialister;
	real alpha__Fusicatenibacter;
	real epsilon__Fusicatenibacter;
	real beta__Fusicatenibacter_Others;
	real beta__Fusicatenibacter_Blautia;
	real beta__Fusicatenibacter_Faecalibacterium;
	real beta__Fusicatenibacter_Bifidobacterium;
	real beta__Fusicatenibacter_Dorea;
	real beta__Fusicatenibacter_Bacteroides;
	real beta__Fusicatenibacter_Roseburia;
	real beta__Fusicatenibacter_Eubacterium;
	real beta__Fusicatenibacter_Prevotella;
	real beta__Fusicatenibacter_Fusicatenibacter;
	real beta__Fusicatenibacter_Anaerostipes;
	real beta__Fusicatenibacter_Coprococcus;
	real beta__Fusicatenibacter_Akkermansia;
	real beta__Fusicatenibacter_Ruminococcus;
	real beta__Fusicatenibacter_Collinsella;
	real beta__Fusicatenibacter_Gemmiger;
	real beta__Fusicatenibacter_Alistipes;
	real beta__Fusicatenibacter_Clostridium;
	real beta__Fusicatenibacter_Holdemanella;
	real beta__Fusicatenibacter_Dialister;
	real alpha__Anaerostipes;
	real epsilon__Anaerostipes;
	real beta__Anaerostipes_Others;
	real beta__Anaerostipes_Blautia;
	real beta__Anaerostipes_Faecalibacterium;
	real beta__Anaerostipes_Bifidobacterium;
	real beta__Anaerostipes_Dorea;
	real beta__Anaerostipes_Bacteroides;
	real beta__Anaerostipes_Roseburia;
	real beta__Anaerostipes_Eubacterium;
	real beta__Anaerostipes_Prevotella;
	real beta__Anaerostipes_Fusicatenibacter;
	real beta__Anaerostipes_Anaerostipes;
	real beta__Anaerostipes_Coprococcus;
	real beta__Anaerostipes_Akkermansia;
	real beta__Anaerostipes_Ruminococcus;
	real beta__Anaerostipes_Collinsella;
	real beta__Anaerostipes_Gemmiger;
	real beta__Anaerostipes_Alistipes;
	real beta__Anaerostipes_Clostridium;
	real beta__Anaerostipes_Holdemanella;
	real beta__Anaerostipes_Dialister;
	real alpha__Coprococcus;
	real epsilon__Coprococcus;
	real beta__Coprococcus_Others;
	real beta__Coprococcus_Blautia;
	real beta__Coprococcus_Faecalibacterium;
	real beta__Coprococcus_Bifidobacterium;
	real beta__Coprococcus_Dorea;
	real beta__Coprococcus_Bacteroides;
	real beta__Coprococcus_Roseburia;
	real beta__Coprococcus_Eubacterium;
	real beta__Coprococcus_Prevotella;
	real beta__Coprococcus_Fusicatenibacter;
	real beta__Coprococcus_Anaerostipes;
	real beta__Coprococcus_Coprococcus;
	real beta__Coprococcus_Akkermansia;
	real beta__Coprococcus_Ruminococcus;
	real beta__Coprococcus_Collinsella;
	real beta__Coprococcus_Gemmiger;
	real beta__Coprococcus_Alistipes;
	real beta__Coprococcus_Clostridium;
	real beta__Coprococcus_Holdemanella;
	real beta__Coprococcus_Dialister;
	real alpha__Akkermansia;
	real epsilon__Akkermansia;
	real beta__Akkermansia_Others;
	real beta__Akkermansia_Blautia;
	real beta__Akkermansia_Faecalibacterium;
	real beta__Akkermansia_Bifidobacterium;
	real beta__Akkermansia_Dorea;
	real beta__Akkermansia_Bacteroides;
	real beta__Akkermansia_Roseburia;
	real beta__Akkermansia_Eubacterium;
	real beta__Akkermansia_Prevotella;
	real beta__Akkermansia_Fusicatenibacter;
	real beta__Akkermansia_Anaerostipes;
	real beta__Akkermansia_Coprococcus;
	real beta__Akkermansia_Akkermansia;
	real beta__Akkermansia_Ruminococcus;
	real beta__Akkermansia_Collinsella;
	real beta__Akkermansia_Gemmiger;
	real beta__Akkermansia_Alistipes;
	real beta__Akkermansia_Clostridium;
	real beta__Akkermansia_Holdemanella;
	real beta__Akkermansia_Dialister;
	real alpha__Ruminococcus;
	real epsilon__Ruminococcus;
	real beta__Ruminococcus_Others;
	real beta__Ruminococcus_Blautia;
	real beta__Ruminococcus_Faecalibacterium;
	real beta__Ruminococcus_Bifidobacterium;
	real beta__Ruminococcus_Dorea;
	real beta__Ruminococcus_Bacteroides;
	real beta__Ruminococcus_Roseburia;
	real beta__Ruminococcus_Eubacterium;
	real beta__Ruminococcus_Prevotella;
	real beta__Ruminococcus_Fusicatenibacter;
	real beta__Ruminococcus_Anaerostipes;
	real beta__Ruminococcus_Coprococcus;
	real beta__Ruminococcus_Akkermansia;
	real beta__Ruminococcus_Ruminococcus;
	real beta__Ruminococcus_Collinsella;
	real beta__Ruminococcus_Gemmiger;
	real beta__Ruminococcus_Alistipes;
	real beta__Ruminococcus_Clostridium;
	real beta__Ruminococcus_Holdemanella;
	real beta__Ruminococcus_Dialister;
	real alpha__Collinsella;
	real epsilon__Collinsella;
	real beta__Collinsella_Others;
	real beta__Collinsella_Blautia;
	real beta__Collinsella_Faecalibacterium;
	real beta__Collinsella_Bifidobacterium;
	real beta__Collinsella_Dorea;
	real beta__Collinsella_Bacteroides;
	real beta__Collinsella_Roseburia;
	real beta__Collinsella_Eubacterium;
	real beta__Collinsella_Prevotella;
	real beta__Collinsella_Fusicatenibacter;
	real beta__Collinsella_Anaerostipes;
	real beta__Collinsella_Coprococcus;
	real beta__Collinsella_Akkermansia;
	real beta__Collinsella_Ruminococcus;
	real beta__Collinsella_Collinsella;
	real beta__Collinsella_Gemmiger;
	real beta__Collinsella_Alistipes;
	real beta__Collinsella_Clostridium;
	real beta__Collinsella_Holdemanella;
	real beta__Collinsella_Dialister;
	real alpha__Gemmiger;
	real epsilon__Gemmiger;
	real beta__Gemmiger_Others;
	real beta__Gemmiger_Blautia;
	real beta__Gemmiger_Faecalibacterium;
	real beta__Gemmiger_Bifidobacterium;
	real beta__Gemmiger_Dorea;
	real beta__Gemmiger_Bacteroides;
	real beta__Gemmiger_Roseburia;
	real beta__Gemmiger_Eubacterium;
	real beta__Gemmiger_Prevotella;
	real beta__Gemmiger_Fusicatenibacter;
	real beta__Gemmiger_Anaerostipes;
	real beta__Gemmiger_Coprococcus;
	real beta__Gemmiger_Akkermansia;
	real beta__Gemmiger_Ruminococcus;
	real beta__Gemmiger_Collinsella;
	real beta__Gemmiger_Gemmiger;
	real beta__Gemmiger_Alistipes;
	real beta__Gemmiger_Clostridium;
	real beta__Gemmiger_Holdemanella;
	real beta__Gemmiger_Dialister;
	real alpha__Alistipes;
	real epsilon__Alistipes;
	real beta__Alistipes_Others;
	real beta__Alistipes_Blautia;
	real beta__Alistipes_Faecalibacterium;
	real beta__Alistipes_Bifidobacterium;
	real beta__Alistipes_Dorea;
	real beta__Alistipes_Bacteroides;
	real beta__Alistipes_Roseburia;
	real beta__Alistipes_Eubacterium;
	real beta__Alistipes_Prevotella;
	real beta__Alistipes_Fusicatenibacter;
	real beta__Alistipes_Anaerostipes;
	real beta__Alistipes_Coprococcus;
	real beta__Alistipes_Akkermansia;
	real beta__Alistipes_Ruminococcus;
	real beta__Alistipes_Collinsella;
	real beta__Alistipes_Gemmiger;
	real beta__Alistipes_Alistipes;
	real beta__Alistipes_Clostridium;
	real beta__Alistipes_Holdemanella;
	real beta__Alistipes_Dialister;
	real alpha__Clostridium;
	real epsilon__Clostridium;
	real beta__Clostridium_Others;
	real beta__Clostridium_Blautia;
	real beta__Clostridium_Faecalibacterium;
	real beta__Clostridium_Bifidobacterium;
	real beta__Clostridium_Dorea;
	real beta__Clostridium_Bacteroides;
	real beta__Clostridium_Roseburia;
	real beta__Clostridium_Eubacterium;
	real beta__Clostridium_Prevotella;
	real beta__Clostridium_Fusicatenibacter;
	real beta__Clostridium_Anaerostipes;
	real beta__Clostridium_Coprococcus;
	real beta__Clostridium_Akkermansia;
	real beta__Clostridium_Ruminococcus;
	real beta__Clostridium_Collinsella;
	real beta__Clostridium_Gemmiger;
	real beta__Clostridium_Alistipes;
	real beta__Clostridium_Clostridium;
	real beta__Clostridium_Holdemanella;
	real beta__Clostridium_Dialister;
	real alpha__Holdemanella;
	real epsilon__Holdemanella;
	real beta__Holdemanella_Others;
	real beta__Holdemanella_Blautia;
	real beta__Holdemanella_Faecalibacterium;
	real beta__Holdemanella_Bifidobacterium;
	real beta__Holdemanella_Dorea;
	real beta__Holdemanella_Bacteroides;
	real beta__Holdemanella_Roseburia;
	real beta__Holdemanella_Eubacterium;
	real beta__Holdemanella_Prevotella;
	real beta__Holdemanella_Fusicatenibacter;
	real beta__Holdemanella_Anaerostipes;
	real beta__Holdemanella_Coprococcus;
	real beta__Holdemanella_Akkermansia;
	real beta__Holdemanella_Ruminococcus;
	real beta__Holdemanella_Collinsella;
	real beta__Holdemanella_Gemmiger;
	real beta__Holdemanella_Alistipes;
	real beta__Holdemanella_Clostridium;
	real beta__Holdemanella_Holdemanella;
	real beta__Holdemanella_Dialister;
	real alpha__Dialister;
	real epsilon__Dialister;
	real beta__Dialister_Others;
	real beta__Dialister_Blautia;
	real beta__Dialister_Faecalibacterium;
	real beta__Dialister_Bifidobacterium;
	real beta__Dialister_Dorea;
	real beta__Dialister_Bacteroides;
	real beta__Dialister_Roseburia;
	real beta__Dialister_Eubacterium;
	real beta__Dialister_Prevotella;
	real beta__Dialister_Fusicatenibacter;
	real beta__Dialister_Anaerostipes;
	real beta__Dialister_Coprococcus;
	real beta__Dialister_Akkermansia;
	real beta__Dialister_Ruminococcus;
	real beta__Dialister_Collinsella;
	real beta__Dialister_Gemmiger;
	real beta__Dialister_Alistipes;
	real beta__Dialister_Clostridium;
	real beta__Dialister_Holdemanella;
	real beta__Dialister_Dialister;
}
model {
	sigma ~ uniform(0,1);
	alpha__Others ~ normal(0,1);
	epsilon__Others ~ normal(0,1);
	beta__Others_Others ~ normal(0,1);
	beta__Others_Blautia ~ normal(0,1);
	beta__Others_Faecalibacterium ~ normal(0,1);
	beta__Others_Bifidobacterium ~ normal(0,1);
	beta__Others_Dorea ~ normal(0,1);
	beta__Others_Bacteroides ~ normal(0,1);
	beta__Others_Roseburia ~ normal(0,1);
	beta__Others_Eubacterium ~ normal(0,1);
	beta__Others_Prevotella ~ normal(0,1);
	beta__Others_Fusicatenibacter ~ normal(0,1);
	beta__Others_Anaerostipes ~ normal(0,1);
	beta__Others_Coprococcus ~ normal(0,1);
	beta__Others_Akkermansia ~ normal(0,1);
	beta__Others_Ruminococcus ~ normal(0,1);
	beta__Others_Collinsella ~ normal(0,1);
	beta__Others_Gemmiger ~ normal(0,1);
	beta__Others_Alistipes ~ normal(0,1);
	beta__Others_Clostridium ~ normal(0,1);
	beta__Others_Holdemanella ~ normal(0,1);
	beta__Others_Dialister ~ normal(0,1);
	alpha__Blautia ~ normal(0,1);
	epsilon__Blautia ~ normal(0,1);
	beta__Blautia_Others ~ normal(0,1);
	beta__Blautia_Blautia ~ normal(0,1);
	beta__Blautia_Faecalibacterium ~ normal(0,1);
	beta__Blautia_Bifidobacterium ~ normal(0,1);
	beta__Blautia_Dorea ~ normal(0,1);
	beta__Blautia_Bacteroides ~ normal(0,1);
	beta__Blautia_Roseburia ~ normal(0,1);
	beta__Blautia_Eubacterium ~ normal(0,1);
	beta__Blautia_Prevotella ~ normal(0,1);
	beta__Blautia_Fusicatenibacter ~ normal(0,1);
	beta__Blautia_Anaerostipes ~ normal(0,1);
	beta__Blautia_Coprococcus ~ normal(0,1);
	beta__Blautia_Akkermansia ~ normal(0,1);
	beta__Blautia_Ruminococcus ~ normal(0,1);
	beta__Blautia_Collinsella ~ normal(0,1);
	beta__Blautia_Gemmiger ~ normal(0,1);
	beta__Blautia_Alistipes ~ normal(0,1);
	beta__Blautia_Clostridium ~ normal(0,1);
	beta__Blautia_Holdemanella ~ normal(0,1);
	beta__Blautia_Dialister ~ normal(0,1);
	alpha__Faecalibacterium ~ normal(0,1);
	epsilon__Faecalibacterium ~ normal(0,1);
	beta__Faecalibacterium_Others ~ normal(0,1);
	beta__Faecalibacterium_Blautia ~ normal(0,1);
	beta__Faecalibacterium_Faecalibacterium ~ normal(0,1);
	beta__Faecalibacterium_Bifidobacterium ~ normal(0,1);
	beta__Faecalibacterium_Dorea ~ normal(0,1);
	beta__Faecalibacterium_Bacteroides ~ normal(0,1);
	beta__Faecalibacterium_Roseburia ~ normal(0,1);
	beta__Faecalibacterium_Eubacterium ~ normal(0,1);
	beta__Faecalibacterium_Prevotella ~ normal(0,1);
	beta__Faecalibacterium_Fusicatenibacter ~ normal(0,1);
	beta__Faecalibacterium_Anaerostipes ~ normal(0,1);
	beta__Faecalibacterium_Coprococcus ~ normal(0,1);
	beta__Faecalibacterium_Akkermansia ~ normal(0,1);
	beta__Faecalibacterium_Ruminococcus ~ normal(0,1);
	beta__Faecalibacterium_Collinsella ~ normal(0,1);
	beta__Faecalibacterium_Gemmiger ~ normal(0,1);
	beta__Faecalibacterium_Alistipes ~ normal(0,1);
	beta__Faecalibacterium_Clostridium ~ normal(0,1);
	beta__Faecalibacterium_Holdemanella ~ normal(0,1);
	beta__Faecalibacterium_Dialister ~ normal(0,1);
	alpha__Bifidobacterium ~ normal(0,1);
	epsilon__Bifidobacterium ~ normal(0,1);
	beta__Bifidobacterium_Others ~ normal(0,1);
	beta__Bifidobacterium_Blautia ~ normal(0,1);
	beta__Bifidobacterium_Faecalibacterium ~ normal(0,1);
	beta__Bifidobacterium_Bifidobacterium ~ normal(0,1);
	beta__Bifidobacterium_Dorea ~ normal(0,1);
	beta__Bifidobacterium_Bacteroides ~ normal(0,1);
	beta__Bifidobacterium_Roseburia ~ normal(0,1);
	beta__Bifidobacterium_Eubacterium ~ normal(0,1);
	beta__Bifidobacterium_Prevotella ~ normal(0,1);
	beta__Bifidobacterium_Fusicatenibacter ~ normal(0,1);
	beta__Bifidobacterium_Anaerostipes ~ normal(0,1);
	beta__Bifidobacterium_Coprococcus ~ normal(0,1);
	beta__Bifidobacterium_Akkermansia ~ normal(0,1);
	beta__Bifidobacterium_Ruminococcus ~ normal(0,1);
	beta__Bifidobacterium_Collinsella ~ normal(0,1);
	beta__Bifidobacterium_Gemmiger ~ normal(0,1);
	beta__Bifidobacterium_Alistipes ~ normal(0,1);
	beta__Bifidobacterium_Clostridium ~ normal(0,1);
	beta__Bifidobacterium_Holdemanella ~ normal(0,1);
	beta__Bifidobacterium_Dialister ~ normal(0,1);
	alpha__Dorea ~ normal(0,1);
	epsilon__Dorea ~ normal(0,1);
	beta__Dorea_Others ~ normal(0,1);
	beta__Dorea_Blautia ~ normal(0,1);
	beta__Dorea_Faecalibacterium ~ normal(0,1);
	beta__Dorea_Bifidobacterium ~ normal(0,1);
	beta__Dorea_Dorea ~ normal(0,1);
	beta__Dorea_Bacteroides ~ normal(0,1);
	beta__Dorea_Roseburia ~ normal(0,1);
	beta__Dorea_Eubacterium ~ normal(0,1);
	beta__Dorea_Prevotella ~ normal(0,1);
	beta__Dorea_Fusicatenibacter ~ normal(0,1);
	beta__Dorea_Anaerostipes ~ normal(0,1);
	beta__Dorea_Coprococcus ~ normal(0,1);
	beta__Dorea_Akkermansia ~ normal(0,1);
	beta__Dorea_Ruminococcus ~ normal(0,1);
	beta__Dorea_Collinsella ~ normal(0,1);
	beta__Dorea_Gemmiger ~ normal(0,1);
	beta__Dorea_Alistipes ~ normal(0,1);
	beta__Dorea_Clostridium ~ normal(0,1);
	beta__Dorea_Holdemanella ~ normal(0,1);
	beta__Dorea_Dialister ~ normal(0,1);
	alpha__Bacteroides ~ normal(0,1);
	epsilon__Bacteroides ~ normal(0,1);
	beta__Bacteroides_Others ~ normal(0,1);
	beta__Bacteroides_Blautia ~ normal(0,1);
	beta__Bacteroides_Faecalibacterium ~ normal(0,1);
	beta__Bacteroides_Bifidobacterium ~ normal(0,1);
	beta__Bacteroides_Dorea ~ normal(0,1);
	beta__Bacteroides_Bacteroides ~ normal(0,1);
	beta__Bacteroides_Roseburia ~ normal(0,1);
	beta__Bacteroides_Eubacterium ~ normal(0,1);
	beta__Bacteroides_Prevotella ~ normal(0,1);
	beta__Bacteroides_Fusicatenibacter ~ normal(0,1);
	beta__Bacteroides_Anaerostipes ~ normal(0,1);
	beta__Bacteroides_Coprococcus ~ normal(0,1);
	beta__Bacteroides_Akkermansia ~ normal(0,1);
	beta__Bacteroides_Ruminococcus ~ normal(0,1);
	beta__Bacteroides_Collinsella ~ normal(0,1);
	beta__Bacteroides_Gemmiger ~ normal(0,1);
	beta__Bacteroides_Alistipes ~ normal(0,1);
	beta__Bacteroides_Clostridium ~ normal(0,1);
	beta__Bacteroides_Holdemanella ~ normal(0,1);
	beta__Bacteroides_Dialister ~ normal(0,1);
	alpha__Roseburia ~ normal(0,1);
	epsilon__Roseburia ~ normal(0,1);
	beta__Roseburia_Others ~ normal(0,1);
	beta__Roseburia_Blautia ~ normal(0,1);
	beta__Roseburia_Faecalibacterium ~ normal(0,1);
	beta__Roseburia_Bifidobacterium ~ normal(0,1);
	beta__Roseburia_Dorea ~ normal(0,1);
	beta__Roseburia_Bacteroides ~ normal(0,1);
	beta__Roseburia_Roseburia ~ normal(0,1);
	beta__Roseburia_Eubacterium ~ normal(0,1);
	beta__Roseburia_Prevotella ~ normal(0,1);
	beta__Roseburia_Fusicatenibacter ~ normal(0,1);
	beta__Roseburia_Anaerostipes ~ normal(0,1);
	beta__Roseburia_Coprococcus ~ normal(0,1);
	beta__Roseburia_Akkermansia ~ normal(0,1);
	beta__Roseburia_Ruminococcus ~ normal(0,1);
	beta__Roseburia_Collinsella ~ normal(0,1);
	beta__Roseburia_Gemmiger ~ normal(0,1);
	beta__Roseburia_Alistipes ~ normal(0,1);
	beta__Roseburia_Clostridium ~ normal(0,1);
	beta__Roseburia_Holdemanella ~ normal(0,1);
	beta__Roseburia_Dialister ~ normal(0,1);
	alpha__Eubacterium ~ normal(0,1);
	epsilon__Eubacterium ~ normal(0,1);
	beta__Eubacterium_Others ~ normal(0,1);
	beta__Eubacterium_Blautia ~ normal(0,1);
	beta__Eubacterium_Faecalibacterium ~ normal(0,1);
	beta__Eubacterium_Bifidobacterium ~ normal(0,1);
	beta__Eubacterium_Dorea ~ normal(0,1);
	beta__Eubacterium_Bacteroides ~ normal(0,1);
	beta__Eubacterium_Roseburia ~ normal(0,1);
	beta__Eubacterium_Eubacterium ~ normal(0,1);
	beta__Eubacterium_Prevotella ~ normal(0,1);
	beta__Eubacterium_Fusicatenibacter ~ normal(0,1);
	beta__Eubacterium_Anaerostipes ~ normal(0,1);
	beta__Eubacterium_Coprococcus ~ normal(0,1);
	beta__Eubacterium_Akkermansia ~ normal(0,1);
	beta__Eubacterium_Ruminococcus ~ normal(0,1);
	beta__Eubacterium_Collinsella ~ normal(0,1);
	beta__Eubacterium_Gemmiger ~ normal(0,1);
	beta__Eubacterium_Alistipes ~ normal(0,1);
	beta__Eubacterium_Clostridium ~ normal(0,1);
	beta__Eubacterium_Holdemanella ~ normal(0,1);
	beta__Eubacterium_Dialister ~ normal(0,1);
	alpha__Prevotella ~ normal(0,1);
	epsilon__Prevotella ~ normal(0,1);
	beta__Prevotella_Others ~ normal(0,1);
	beta__Prevotella_Blautia ~ normal(0,1);
	beta__Prevotella_Faecalibacterium ~ normal(0,1);
	beta__Prevotella_Bifidobacterium ~ normal(0,1);
	beta__Prevotella_Dorea ~ normal(0,1);
	beta__Prevotella_Bacteroides ~ normal(0,1);
	beta__Prevotella_Roseburia ~ normal(0,1);
	beta__Prevotella_Eubacterium ~ normal(0,1);
	beta__Prevotella_Prevotella ~ normal(0,1);
	beta__Prevotella_Fusicatenibacter ~ normal(0,1);
	beta__Prevotella_Anaerostipes ~ normal(0,1);
	beta__Prevotella_Coprococcus ~ normal(0,1);
	beta__Prevotella_Akkermansia ~ normal(0,1);
	beta__Prevotella_Ruminococcus ~ normal(0,1);
	beta__Prevotella_Collinsella ~ normal(0,1);
	beta__Prevotella_Gemmiger ~ normal(0,1);
	beta__Prevotella_Alistipes ~ normal(0,1);
	beta__Prevotella_Clostridium ~ normal(0,1);
	beta__Prevotella_Holdemanella ~ normal(0,1);
	beta__Prevotella_Dialister ~ normal(0,1);
	alpha__Fusicatenibacter ~ normal(0,1);
	epsilon__Fusicatenibacter ~ normal(0,1);
	beta__Fusicatenibacter_Others ~ normal(0,1);
	beta__Fusicatenibacter_Blautia ~ normal(0,1);
	beta__Fusicatenibacter_Faecalibacterium ~ normal(0,1);
	beta__Fusicatenibacter_Bifidobacterium ~ normal(0,1);
	beta__Fusicatenibacter_Dorea ~ normal(0,1);
	beta__Fusicatenibacter_Bacteroides ~ normal(0,1);
	beta__Fusicatenibacter_Roseburia ~ normal(0,1);
	beta__Fusicatenibacter_Eubacterium ~ normal(0,1);
	beta__Fusicatenibacter_Prevotella ~ normal(0,1);
	beta__Fusicatenibacter_Fusicatenibacter ~ normal(0,1);
	beta__Fusicatenibacter_Anaerostipes ~ normal(0,1);
	beta__Fusicatenibacter_Coprococcus ~ normal(0,1);
	beta__Fusicatenibacter_Akkermansia ~ normal(0,1);
	beta__Fusicatenibacter_Ruminococcus ~ normal(0,1);
	beta__Fusicatenibacter_Collinsella ~ normal(0,1);
	beta__Fusicatenibacter_Gemmiger ~ normal(0,1);
	beta__Fusicatenibacter_Alistipes ~ normal(0,1);
	beta__Fusicatenibacter_Clostridium ~ normal(0,1);
	beta__Fusicatenibacter_Holdemanella ~ normal(0,1);
	beta__Fusicatenibacter_Dialister ~ normal(0,1);
	alpha__Anaerostipes ~ normal(0,1);
	epsilon__Anaerostipes ~ normal(0,1);
	beta__Anaerostipes_Others ~ normal(0,1);
	beta__Anaerostipes_Blautia ~ normal(0,1);
	beta__Anaerostipes_Faecalibacterium ~ normal(0,1);
	beta__Anaerostipes_Bifidobacterium ~ normal(0,1);
	beta__Anaerostipes_Dorea ~ normal(0,1);
	beta__Anaerostipes_Bacteroides ~ normal(0,1);
	beta__Anaerostipes_Roseburia ~ normal(0,1);
	beta__Anaerostipes_Eubacterium ~ normal(0,1);
	beta__Anaerostipes_Prevotella ~ normal(0,1);
	beta__Anaerostipes_Fusicatenibacter ~ normal(0,1);
	beta__Anaerostipes_Anaerostipes ~ normal(0,1);
	beta__Anaerostipes_Coprococcus ~ normal(0,1);
	beta__Anaerostipes_Akkermansia ~ normal(0,1);
	beta__Anaerostipes_Ruminococcus ~ normal(0,1);
	beta__Anaerostipes_Collinsella ~ normal(0,1);
	beta__Anaerostipes_Gemmiger ~ normal(0,1);
	beta__Anaerostipes_Alistipes ~ normal(0,1);
	beta__Anaerostipes_Clostridium ~ normal(0,1);
	beta__Anaerostipes_Holdemanella ~ normal(0,1);
	beta__Anaerostipes_Dialister ~ normal(0,1);
	alpha__Coprococcus ~ normal(0,1);
	epsilon__Coprococcus ~ normal(0,1);
	beta__Coprococcus_Others ~ normal(0,1);
	beta__Coprococcus_Blautia ~ normal(0,1);
	beta__Coprococcus_Faecalibacterium ~ normal(0,1);
	beta__Coprococcus_Bifidobacterium ~ normal(0,1);
	beta__Coprococcus_Dorea ~ normal(0,1);
	beta__Coprococcus_Bacteroides ~ normal(0,1);
	beta__Coprococcus_Roseburia ~ normal(0,1);
	beta__Coprococcus_Eubacterium ~ normal(0,1);
	beta__Coprococcus_Prevotella ~ normal(0,1);
	beta__Coprococcus_Fusicatenibacter ~ normal(0,1);
	beta__Coprococcus_Anaerostipes ~ normal(0,1);
	beta__Coprococcus_Coprococcus ~ normal(0,1);
	beta__Coprococcus_Akkermansia ~ normal(0,1);
	beta__Coprococcus_Ruminococcus ~ normal(0,1);
	beta__Coprococcus_Collinsella ~ normal(0,1);
	beta__Coprococcus_Gemmiger ~ normal(0,1);
	beta__Coprococcus_Alistipes ~ normal(0,1);
	beta__Coprococcus_Clostridium ~ normal(0,1);
	beta__Coprococcus_Holdemanella ~ normal(0,1);
	beta__Coprococcus_Dialister ~ normal(0,1);
	alpha__Akkermansia ~ normal(0,1);
	epsilon__Akkermansia ~ normal(0,1);
	beta__Akkermansia_Others ~ normal(0,1);
	beta__Akkermansia_Blautia ~ normal(0,1);
	beta__Akkermansia_Faecalibacterium ~ normal(0,1);
	beta__Akkermansia_Bifidobacterium ~ normal(0,1);
	beta__Akkermansia_Dorea ~ normal(0,1);
	beta__Akkermansia_Bacteroides ~ normal(0,1);
	beta__Akkermansia_Roseburia ~ normal(0,1);
	beta__Akkermansia_Eubacterium ~ normal(0,1);
	beta__Akkermansia_Prevotella ~ normal(0,1);
	beta__Akkermansia_Fusicatenibacter ~ normal(0,1);
	beta__Akkermansia_Anaerostipes ~ normal(0,1);
	beta__Akkermansia_Coprococcus ~ normal(0,1);
	beta__Akkermansia_Akkermansia ~ normal(0,1);
	beta__Akkermansia_Ruminococcus ~ normal(0,1);
	beta__Akkermansia_Collinsella ~ normal(0,1);
	beta__Akkermansia_Gemmiger ~ normal(0,1);
	beta__Akkermansia_Alistipes ~ normal(0,1);
	beta__Akkermansia_Clostridium ~ normal(0,1);
	beta__Akkermansia_Holdemanella ~ normal(0,1);
	beta__Akkermansia_Dialister ~ normal(0,1);
	alpha__Ruminococcus ~ normal(0,1);
	epsilon__Ruminococcus ~ normal(0,1);
	beta__Ruminococcus_Others ~ normal(0,1);
	beta__Ruminococcus_Blautia ~ normal(0,1);
	beta__Ruminococcus_Faecalibacterium ~ normal(0,1);
	beta__Ruminococcus_Bifidobacterium ~ normal(0,1);
	beta__Ruminococcus_Dorea ~ normal(0,1);
	beta__Ruminococcus_Bacteroides ~ normal(0,1);
	beta__Ruminococcus_Roseburia ~ normal(0,1);
	beta__Ruminococcus_Eubacterium ~ normal(0,1);
	beta__Ruminococcus_Prevotella ~ normal(0,1);
	beta__Ruminococcus_Fusicatenibacter ~ normal(0,1);
	beta__Ruminococcus_Anaerostipes ~ normal(0,1);
	beta__Ruminococcus_Coprococcus ~ normal(0,1);
	beta__Ruminococcus_Akkermansia ~ normal(0,1);
	beta__Ruminococcus_Ruminococcus ~ normal(0,1);
	beta__Ruminococcus_Collinsella ~ normal(0,1);
	beta__Ruminococcus_Gemmiger ~ normal(0,1);
	beta__Ruminococcus_Alistipes ~ normal(0,1);
	beta__Ruminococcus_Clostridium ~ normal(0,1);
	beta__Ruminococcus_Holdemanella ~ normal(0,1);
	beta__Ruminococcus_Dialister ~ normal(0,1);
	alpha__Collinsella ~ normal(0,1);
	epsilon__Collinsella ~ normal(0,1);
	beta__Collinsella_Others ~ normal(0,1);
	beta__Collinsella_Blautia ~ normal(0,1);
	beta__Collinsella_Faecalibacterium ~ normal(0,1);
	beta__Collinsella_Bifidobacterium ~ normal(0,1);
	beta__Collinsella_Dorea ~ normal(0,1);
	beta__Collinsella_Bacteroides ~ normal(0,1);
	beta__Collinsella_Roseburia ~ normal(0,1);
	beta__Collinsella_Eubacterium ~ normal(0,1);
	beta__Collinsella_Prevotella ~ normal(0,1);
	beta__Collinsella_Fusicatenibacter ~ normal(0,1);
	beta__Collinsella_Anaerostipes ~ normal(0,1);
	beta__Collinsella_Coprococcus ~ normal(0,1);
	beta__Collinsella_Akkermansia ~ normal(0,1);
	beta__Collinsella_Ruminococcus ~ normal(0,1);
	beta__Collinsella_Collinsella ~ normal(0,1);
	beta__Collinsella_Gemmiger ~ normal(0,1);
	beta__Collinsella_Alistipes ~ normal(0,1);
	beta__Collinsella_Clostridium ~ normal(0,1);
	beta__Collinsella_Holdemanella ~ normal(0,1);
	beta__Collinsella_Dialister ~ normal(0,1);
	alpha__Gemmiger ~ normal(0,1);
	epsilon__Gemmiger ~ normal(0,1);
	beta__Gemmiger_Others ~ normal(0,1);
	beta__Gemmiger_Blautia ~ normal(0,1);
	beta__Gemmiger_Faecalibacterium ~ normal(0,1);
	beta__Gemmiger_Bifidobacterium ~ normal(0,1);
	beta__Gemmiger_Dorea ~ normal(0,1);
	beta__Gemmiger_Bacteroides ~ normal(0,1);
	beta__Gemmiger_Roseburia ~ normal(0,1);
	beta__Gemmiger_Eubacterium ~ normal(0,1);
	beta__Gemmiger_Prevotella ~ normal(0,1);
	beta__Gemmiger_Fusicatenibacter ~ normal(0,1);
	beta__Gemmiger_Anaerostipes ~ normal(0,1);
	beta__Gemmiger_Coprococcus ~ normal(0,1);
	beta__Gemmiger_Akkermansia ~ normal(0,1);
	beta__Gemmiger_Ruminococcus ~ normal(0,1);
	beta__Gemmiger_Collinsella ~ normal(0,1);
	beta__Gemmiger_Gemmiger ~ normal(0,1);
	beta__Gemmiger_Alistipes ~ normal(0,1);
	beta__Gemmiger_Clostridium ~ normal(0,1);
	beta__Gemmiger_Holdemanella ~ normal(0,1);
	beta__Gemmiger_Dialister ~ normal(0,1);
	alpha__Alistipes ~ normal(0,1);
	epsilon__Alistipes ~ normal(0,1);
	beta__Alistipes_Others ~ normal(0,1);
	beta__Alistipes_Blautia ~ normal(0,1);
	beta__Alistipes_Faecalibacterium ~ normal(0,1);
	beta__Alistipes_Bifidobacterium ~ normal(0,1);
	beta__Alistipes_Dorea ~ normal(0,1);
	beta__Alistipes_Bacteroides ~ normal(0,1);
	beta__Alistipes_Roseburia ~ normal(0,1);
	beta__Alistipes_Eubacterium ~ normal(0,1);
	beta__Alistipes_Prevotella ~ normal(0,1);
	beta__Alistipes_Fusicatenibacter ~ normal(0,1);
	beta__Alistipes_Anaerostipes ~ normal(0,1);
	beta__Alistipes_Coprococcus ~ normal(0,1);
	beta__Alistipes_Akkermansia ~ normal(0,1);
	beta__Alistipes_Ruminococcus ~ normal(0,1);
	beta__Alistipes_Collinsella ~ normal(0,1);
	beta__Alistipes_Gemmiger ~ normal(0,1);
	beta__Alistipes_Alistipes ~ normal(0,1);
	beta__Alistipes_Clostridium ~ normal(0,1);
	beta__Alistipes_Holdemanella ~ normal(0,1);
	beta__Alistipes_Dialister ~ normal(0,1);
	alpha__Clostridium ~ normal(0,1);
	epsilon__Clostridium ~ normal(0,1);
	beta__Clostridium_Others ~ normal(0,1);
	beta__Clostridium_Blautia ~ normal(0,1);
	beta__Clostridium_Faecalibacterium ~ normal(0,1);
	beta__Clostridium_Bifidobacterium ~ normal(0,1);
	beta__Clostridium_Dorea ~ normal(0,1);
	beta__Clostridium_Bacteroides ~ normal(0,1);
	beta__Clostridium_Roseburia ~ normal(0,1);
	beta__Clostridium_Eubacterium ~ normal(0,1);
	beta__Clostridium_Prevotella ~ normal(0,1);
	beta__Clostridium_Fusicatenibacter ~ normal(0,1);
	beta__Clostridium_Anaerostipes ~ normal(0,1);
	beta__Clostridium_Coprococcus ~ normal(0,1);
	beta__Clostridium_Akkermansia ~ normal(0,1);
	beta__Clostridium_Ruminococcus ~ normal(0,1);
	beta__Clostridium_Collinsella ~ normal(0,1);
	beta__Clostridium_Gemmiger ~ normal(0,1);
	beta__Clostridium_Alistipes ~ normal(0,1);
	beta__Clostridium_Clostridium ~ normal(0,1);
	beta__Clostridium_Holdemanella ~ normal(0,1);
	beta__Clostridium_Dialister ~ normal(0,1);
	alpha__Holdemanella ~ normal(0,1);
	epsilon__Holdemanella ~ normal(0,1);
	beta__Holdemanella_Others ~ normal(0,1);
	beta__Holdemanella_Blautia ~ normal(0,1);
	beta__Holdemanella_Faecalibacterium ~ normal(0,1);
	beta__Holdemanella_Bifidobacterium ~ normal(0,1);
	beta__Holdemanella_Dorea ~ normal(0,1);
	beta__Holdemanella_Bacteroides ~ normal(0,1);
	beta__Holdemanella_Roseburia ~ normal(0,1);
	beta__Holdemanella_Eubacterium ~ normal(0,1);
	beta__Holdemanella_Prevotella ~ normal(0,1);
	beta__Holdemanella_Fusicatenibacter ~ normal(0,1);
	beta__Holdemanella_Anaerostipes ~ normal(0,1);
	beta__Holdemanella_Coprococcus ~ normal(0,1);
	beta__Holdemanella_Akkermansia ~ normal(0,1);
	beta__Holdemanella_Ruminococcus ~ normal(0,1);
	beta__Holdemanella_Collinsella ~ normal(0,1);
	beta__Holdemanella_Gemmiger ~ normal(0,1);
	beta__Holdemanella_Alistipes ~ normal(0,1);
	beta__Holdemanella_Clostridium ~ normal(0,1);
	beta__Holdemanella_Holdemanella ~ normal(0,1);
	beta__Holdemanella_Dialister ~ normal(0,1);
	alpha__Dialister ~ normal(0,1);
	epsilon__Dialister ~ normal(0,1);
	beta__Dialister_Others ~ normal(0,1);
	beta__Dialister_Blautia ~ normal(0,1);
	beta__Dialister_Faecalibacterium ~ normal(0,1);
	beta__Dialister_Bifidobacterium ~ normal(0,1);
	beta__Dialister_Dorea ~ normal(0,1);
	beta__Dialister_Bacteroides ~ normal(0,1);
	beta__Dialister_Roseburia ~ normal(0,1);
	beta__Dialister_Eubacterium ~ normal(0,1);
	beta__Dialister_Prevotella ~ normal(0,1);
	beta__Dialister_Fusicatenibacter ~ normal(0,1);
	beta__Dialister_Anaerostipes ~ normal(0,1);
	beta__Dialister_Coprococcus ~ normal(0,1);
	beta__Dialister_Akkermansia ~ normal(0,1);
	beta__Dialister_Ruminococcus ~ normal(0,1);
	beta__Dialister_Collinsella ~ normal(0,1);
	beta__Dialister_Gemmiger ~ normal(0,1);
	beta__Dialister_Alistipes ~ normal(0,1);
	beta__Dialister_Clostridium ~ normal(0,1);
	beta__Dialister_Holdemanella ~ normal(0,1);
	beta__Dialister_Dialister ~ normal(0,1);
	dlogX ~ normal(alpha__Others*growth_rate_Others+epsilon__Others*fiber_response_Others+beta__Others_Others*pairwise_interaction_Others_Others+beta__Others_Blautia*pairwise_interaction_Others_Blautia+beta__Others_Faecalibacterium*pairwise_interaction_Others_Faecalibacterium+beta__Others_Bifidobacterium*pairwise_interaction_Others_Bifidobacterium+beta__Others_Dorea*pairwise_interaction_Others_Dorea+beta__Others_Bacteroides*pairwise_interaction_Others_Bacteroides+beta__Others_Roseburia*pairwise_interaction_Others_Roseburia+beta__Others_Eubacterium*pairwise_interaction_Others_Eubacterium+beta__Others_Prevotella*pairwise_interaction_Others_Prevotella+beta__Others_Fusicatenibacter*pairwise_interaction_Others_Fusicatenibacter+beta__Others_Anaerostipes*pairwise_interaction_Others_Anaerostipes+beta__Others_Coprococcus*pairwise_interaction_Others_Coprococcus+beta__Others_Akkermansia*pairwise_interaction_Others_Akkermansia+beta__Others_Ruminococcus*pairwise_interaction_Others_Ruminococcus+beta__Others_Collinsella*pairwise_interaction_Others_Collinsella+beta__Others_Gemmiger*pairwise_interaction_Others_Gemmiger+beta__Others_Alistipes*pairwise_interaction_Others_Alistipes+beta__Others_Clostridium*pairwise_interaction_Others_Clostridium+beta__Others_Holdemanella*pairwise_interaction_Others_Holdemanella+beta__Others_Dialister*pairwise_interaction_Others_Dialister+alpha__Blautia*growth_rate_Blautia+epsilon__Blautia*fiber_response_Blautia+beta__Blautia_Others*pairwise_interaction_Blautia_Others+beta__Blautia_Blautia*pairwise_interaction_Blautia_Blautia+beta__Blautia_Faecalibacterium*pairwise_interaction_Blautia_Faecalibacterium+beta__Blautia_Bifidobacterium*pairwise_interaction_Blautia_Bifidobacterium+beta__Blautia_Dorea*pairwise_interaction_Blautia_Dorea+beta__Blautia_Bacteroides*pairwise_interaction_Blautia_Bacteroides+beta__Blautia_Roseburia*pairwise_interaction_Blautia_Roseburia+beta__Blautia_Eubacterium*pairwise_interaction_Blautia_Eubacterium+beta__Blautia_Prevotella*pairwise_interaction_Blautia_Prevotella+beta__Blautia_Fusicatenibacter*pairwise_interaction_Blautia_Fusicatenibacter+beta__Blautia_Anaerostipes*pairwise_interaction_Blautia_Anaerostipes+beta__Blautia_Coprococcus*pairwise_interaction_Blautia_Coprococcus+beta__Blautia_Akkermansia*pairwise_interaction_Blautia_Akkermansia+beta__Blautia_Ruminococcus*pairwise_interaction_Blautia_Ruminococcus+beta__Blautia_Collinsella*pairwise_interaction_Blautia_Collinsella+beta__Blautia_Gemmiger*pairwise_interaction_Blautia_Gemmiger+beta__Blautia_Alistipes*pairwise_interaction_Blautia_Alistipes+beta__Blautia_Clostridium*pairwise_interaction_Blautia_Clostridium+beta__Blautia_Holdemanella*pairwise_interaction_Blautia_Holdemanella+beta__Blautia_Dialister*pairwise_interaction_Blautia_Dialister+alpha__Faecalibacterium*growth_rate_Faecalibacterium+epsilon__Faecalibacterium*fiber_response_Faecalibacterium+beta__Faecalibacterium_Others*pairwise_interaction_Faecalibacterium_Others+beta__Faecalibacterium_Blautia*pairwise_interaction_Faecalibacterium_Blautia+beta__Faecalibacterium_Faecalibacterium*pairwise_interaction_Faecalibacterium_Faecalibacterium+beta__Faecalibacterium_Bifidobacterium*pairwise_interaction_Faecalibacterium_Bifidobacterium+beta__Faecalibacterium_Dorea*pairwise_interaction_Faecalibacterium_Dorea+beta__Faecalibacterium_Bacteroides*pairwise_interaction_Faecalibacterium_Bacteroides+beta__Faecalibacterium_Roseburia*pairwise_interaction_Faecalibacterium_Roseburia+beta__Faecalibacterium_Eubacterium*pairwise_interaction_Faecalibacterium_Eubacterium+beta__Faecalibacterium_Prevotella*pairwise_interaction_Faecalibacterium_Prevotella+beta__Faecalibacterium_Fusicatenibacter*pairwise_interaction_Faecalibacterium_Fusicatenibacter+beta__Faecalibacterium_Anaerostipes*pairwise_interaction_Faecalibacterium_Anaerostipes+beta__Faecalibacterium_Coprococcus*pairwise_interaction_Faecalibacterium_Coprococcus+beta__Faecalibacterium_Akkermansia*pairwise_interaction_Faecalibacterium_Akkermansia+beta__Faecalibacterium_Ruminococcus*pairwise_interaction_Faecalibacterium_Ruminococcus+beta__Faecalibacterium_Collinsella*pairwise_interaction_Faecalibacterium_Collinsella+beta__Faecalibacterium_Gemmiger*pairwise_interaction_Faecalibacterium_Gemmiger+beta__Faecalibacterium_Alistipes*pairwise_interaction_Faecalibacterium_Alistipes+beta__Faecalibacterium_Clostridium*pairwise_interaction_Faecalibacterium_Clostridium+beta__Faecalibacterium_Holdemanella*pairwise_interaction_Faecalibacterium_Holdemanella+beta__Faecalibacterium_Dialister*pairwise_interaction_Faecalibacterium_Dialister+alpha__Bifidobacterium*growth_rate_Bifidobacterium+epsilon__Bifidobacterium*fiber_response_Bifidobacterium+beta__Bifidobacterium_Others*pairwise_interaction_Bifidobacterium_Others+beta__Bifidobacterium_Blautia*pairwise_interaction_Bifidobacterium_Blautia+beta__Bifidobacterium_Faecalibacterium*pairwise_interaction_Bifidobacterium_Faecalibacterium+beta__Bifidobacterium_Bifidobacterium*pairwise_interaction_Bifidobacterium_Bifidobacterium+beta__Bifidobacterium_Dorea*pairwise_interaction_Bifidobacterium_Dorea+beta__Bifidobacterium_Bacteroides*pairwise_interaction_Bifidobacterium_Bacteroides+beta__Bifidobacterium_Roseburia*pairwise_interaction_Bifidobacterium_Roseburia+beta__Bifidobacterium_Eubacterium*pairwise_interaction_Bifidobacterium_Eubacterium+beta__Bifidobacterium_Prevotella*pairwise_interaction_Bifidobacterium_Prevotella+beta__Bifidobacterium_Fusicatenibacter*pairwise_interaction_Bifidobacterium_Fusicatenibacter+beta__Bifidobacterium_Anaerostipes*pairwise_interaction_Bifidobacterium_Anaerostipes+beta__Bifidobacterium_Coprococcus*pairwise_interaction_Bifidobacterium_Coprococcus+beta__Bifidobacterium_Akkermansia*pairwise_interaction_Bifidobacterium_Akkermansia+beta__Bifidobacterium_Ruminococcus*pairwise_interaction_Bifidobacterium_Ruminococcus+beta__Bifidobacterium_Collinsella*pairwise_interaction_Bifidobacterium_Collinsella+beta__Bifidobacterium_Gemmiger*pairwise_interaction_Bifidobacterium_Gemmiger+beta__Bifidobacterium_Alistipes*pairwise_interaction_Bifidobacterium_Alistipes+beta__Bifidobacterium_Clostridium*pairwise_interaction_Bifidobacterium_Clostridium+beta__Bifidobacterium_Holdemanella*pairwise_interaction_Bifidobacterium_Holdemanella+beta__Bifidobacterium_Dialister*pairwise_interaction_Bifidobacterium_Dialister+alpha__Dorea*growth_rate_Dorea+epsilon__Dorea*fiber_response_Dorea+beta__Dorea_Others*pairwise_interaction_Dorea_Others+beta__Dorea_Blautia*pairwise_interaction_Dorea_Blautia+beta__Dorea_Faecalibacterium*pairwise_interaction_Dorea_Faecalibacterium+beta__Dorea_Bifidobacterium*pairwise_interaction_Dorea_Bifidobacterium+beta__Dorea_Dorea*pairwise_interaction_Dorea_Dorea+beta__Dorea_Bacteroides*pairwise_interaction_Dorea_Bacteroides+beta__Dorea_Roseburia*pairwise_interaction_Dorea_Roseburia+beta__Dorea_Eubacterium*pairwise_interaction_Dorea_Eubacterium+beta__Dorea_Prevotella*pairwise_interaction_Dorea_Prevotella+beta__Dorea_Fusicatenibacter*pairwise_interaction_Dorea_Fusicatenibacter+beta__Dorea_Anaerostipes*pairwise_interaction_Dorea_Anaerostipes+beta__Dorea_Coprococcus*pairwise_interaction_Dorea_Coprococcus+beta__Dorea_Akkermansia*pairwise_interaction_Dorea_Akkermansia+beta__Dorea_Ruminococcus*pairwise_interaction_Dorea_Ruminococcus+beta__Dorea_Collinsella*pairwise_interaction_Dorea_Collinsella+beta__Dorea_Gemmiger*pairwise_interaction_Dorea_Gemmiger+beta__Dorea_Alistipes*pairwise_interaction_Dorea_Alistipes+beta__Dorea_Clostridium*pairwise_interaction_Dorea_Clostridium+beta__Dorea_Holdemanella*pairwise_interaction_Dorea_Holdemanella+beta__Dorea_Dialister*pairwise_interaction_Dorea_Dialister+alpha__Bacteroides*growth_rate_Bacteroides+epsilon__Bacteroides*fiber_response_Bacteroides+beta__Bacteroides_Others*pairwise_interaction_Bacteroides_Others+beta__Bacteroides_Blautia*pairwise_interaction_Bacteroides_Blautia+beta__Bacteroides_Faecalibacterium*pairwise_interaction_Bacteroides_Faecalibacterium+beta__Bacteroides_Bifidobacterium*pairwise_interaction_Bacteroides_Bifidobacterium+beta__Bacteroides_Dorea*pairwise_interaction_Bacteroides_Dorea+beta__Bacteroides_Bacteroides*pairwise_interaction_Bacteroides_Bacteroides+beta__Bacteroides_Roseburia*pairwise_interaction_Bacteroides_Roseburia+beta__Bacteroides_Eubacterium*pairwise_interaction_Bacteroides_Eubacterium+beta__Bacteroides_Prevotella*pairwise_interaction_Bacteroides_Prevotella+beta__Bacteroides_Fusicatenibacter*pairwise_interaction_Bacteroides_Fusicatenibacter+beta__Bacteroides_Anaerostipes*pairwise_interaction_Bacteroides_Anaerostipes+beta__Bacteroides_Coprococcus*pairwise_interaction_Bacteroides_Coprococcus+beta__Bacteroides_Akkermansia*pairwise_interaction_Bacteroides_Akkermansia+beta__Bacteroides_Ruminococcus*pairwise_interaction_Bacteroides_Ruminococcus+beta__Bacteroides_Collinsella*pairwise_interaction_Bacteroides_Collinsella+beta__Bacteroides_Gemmiger*pairwise_interaction_Bacteroides_Gemmiger+beta__Bacteroides_Alistipes*pairwise_interaction_Bacteroides_Alistipes+beta__Bacteroides_Clostridium*pairwise_interaction_Bacteroides_Clostridium+beta__Bacteroides_Holdemanella*pairwise_interaction_Bacteroides_Holdemanella+beta__Bacteroides_Dialister*pairwise_interaction_Bacteroides_Dialister+alpha__Roseburia*growth_rate_Roseburia+epsilon__Roseburia*fiber_response_Roseburia+beta__Roseburia_Others*pairwise_interaction_Roseburia_Others+beta__Roseburia_Blautia*pairwise_interaction_Roseburia_Blautia+beta__Roseburia_Faecalibacterium*pairwise_interaction_Roseburia_Faecalibacterium+beta__Roseburia_Bifidobacterium*pairwise_interaction_Roseburia_Bifidobacterium+beta__Roseburia_Dorea*pairwise_interaction_Roseburia_Dorea+beta__Roseburia_Bacteroides*pairwise_interaction_Roseburia_Bacteroides+beta__Roseburia_Roseburia*pairwise_interaction_Roseburia_Roseburia+beta__Roseburia_Eubacterium*pairwise_interaction_Roseburia_Eubacterium+beta__Roseburia_Prevotella*pairwise_interaction_Roseburia_Prevotella+beta__Roseburia_Fusicatenibacter*pairwise_interaction_Roseburia_Fusicatenibacter+beta__Roseburia_Anaerostipes*pairwise_interaction_Roseburia_Anaerostipes+beta__Roseburia_Coprococcus*pairwise_interaction_Roseburia_Coprococcus+beta__Roseburia_Akkermansia*pairwise_interaction_Roseburia_Akkermansia+beta__Roseburia_Ruminococcus*pairwise_interaction_Roseburia_Ruminococcus+beta__Roseburia_Collinsella*pairwise_interaction_Roseburia_Collinsella+beta__Roseburia_Gemmiger*pairwise_interaction_Roseburia_Gemmiger+beta__Roseburia_Alistipes*pairwise_interaction_Roseburia_Alistipes+beta__Roseburia_Clostridium*pairwise_interaction_Roseburia_Clostridium+beta__Roseburia_Holdemanella*pairwise_interaction_Roseburia_Holdemanella+beta__Roseburia_Dialister*pairwise_interaction_Roseburia_Dialister+alpha__Eubacterium*growth_rate_Eubacterium+epsilon__Eubacterium*fiber_response_Eubacterium+beta__Eubacterium_Others*pairwise_interaction_Eubacterium_Others+beta__Eubacterium_Blautia*pairwise_interaction_Eubacterium_Blautia+beta__Eubacterium_Faecalibacterium*pairwise_interaction_Eubacterium_Faecalibacterium+beta__Eubacterium_Bifidobacterium*pairwise_interaction_Eubacterium_Bifidobacterium+beta__Eubacterium_Dorea*pairwise_interaction_Eubacterium_Dorea+beta__Eubacterium_Bacteroides*pairwise_interaction_Eubacterium_Bacteroides+beta__Eubacterium_Roseburia*pairwise_interaction_Eubacterium_Roseburia+beta__Eubacterium_Eubacterium*pairwise_interaction_Eubacterium_Eubacterium+beta__Eubacterium_Prevotella*pairwise_interaction_Eubacterium_Prevotella+beta__Eubacterium_Fusicatenibacter*pairwise_interaction_Eubacterium_Fusicatenibacter+beta__Eubacterium_Anaerostipes*pairwise_interaction_Eubacterium_Anaerostipes+beta__Eubacterium_Coprococcus*pairwise_interaction_Eubacterium_Coprococcus+beta__Eubacterium_Akkermansia*pairwise_interaction_Eubacterium_Akkermansia+beta__Eubacterium_Ruminococcus*pairwise_interaction_Eubacterium_Ruminococcus+beta__Eubacterium_Collinsella*pairwise_interaction_Eubacterium_Collinsella+beta__Eubacterium_Gemmiger*pairwise_interaction_Eubacterium_Gemmiger+beta__Eubacterium_Alistipes*pairwise_interaction_Eubacterium_Alistipes+beta__Eubacterium_Clostridium*pairwise_interaction_Eubacterium_Clostridium+beta__Eubacterium_Holdemanella*pairwise_interaction_Eubacterium_Holdemanella+beta__Eubacterium_Dialister*pairwise_interaction_Eubacterium_Dialister+alpha__Prevotella*growth_rate_Prevotella+epsilon__Prevotella*fiber_response_Prevotella+beta__Prevotella_Others*pairwise_interaction_Prevotella_Others+beta__Prevotella_Blautia*pairwise_interaction_Prevotella_Blautia+beta__Prevotella_Faecalibacterium*pairwise_interaction_Prevotella_Faecalibacterium+beta__Prevotella_Bifidobacterium*pairwise_interaction_Prevotella_Bifidobacterium+beta__Prevotella_Dorea*pairwise_interaction_Prevotella_Dorea+beta__Prevotella_Bacteroides*pairwise_interaction_Prevotella_Bacteroides+beta__Prevotella_Roseburia*pairwise_interaction_Prevotella_Roseburia+beta__Prevotella_Eubacterium*pairwise_interaction_Prevotella_Eubacterium+beta__Prevotella_Prevotella*pairwise_interaction_Prevotella_Prevotella+beta__Prevotella_Fusicatenibacter*pairwise_interaction_Prevotella_Fusicatenibacter+beta__Prevotella_Anaerostipes*pairwise_interaction_Prevotella_Anaerostipes+beta__Prevotella_Coprococcus*pairwise_interaction_Prevotella_Coprococcus+beta__Prevotella_Akkermansia*pairwise_interaction_Prevotella_Akkermansia+beta__Prevotella_Ruminococcus*pairwise_interaction_Prevotella_Ruminococcus+beta__Prevotella_Collinsella*pairwise_interaction_Prevotella_Collinsella+beta__Prevotella_Gemmiger*pairwise_interaction_Prevotella_Gemmiger+beta__Prevotella_Alistipes*pairwise_interaction_Prevotella_Alistipes+beta__Prevotella_Clostridium*pairwise_interaction_Prevotella_Clostridium+beta__Prevotella_Holdemanella*pairwise_interaction_Prevotella_Holdemanella+beta__Prevotella_Dialister*pairwise_interaction_Prevotella_Dialister+alpha__Fusicatenibacter*growth_rate_Fusicatenibacter+epsilon__Fusicatenibacter*fiber_response_Fusicatenibacter+beta__Fusicatenibacter_Others*pairwise_interaction_Fusicatenibacter_Others+beta__Fusicatenibacter_Blautia*pairwise_interaction_Fusicatenibacter_Blautia+beta__Fusicatenibacter_Faecalibacterium*pairwise_interaction_Fusicatenibacter_Faecalibacterium+beta__Fusicatenibacter_Bifidobacterium*pairwise_interaction_Fusicatenibacter_Bifidobacterium+beta__Fusicatenibacter_Dorea*pairwise_interaction_Fusicatenibacter_Dorea+beta__Fusicatenibacter_Bacteroides*pairwise_interaction_Fusicatenibacter_Bacteroides+beta__Fusicatenibacter_Roseburia*pairwise_interaction_Fusicatenibacter_Roseburia+beta__Fusicatenibacter_Eubacterium*pairwise_interaction_Fusicatenibacter_Eubacterium+beta__Fusicatenibacter_Prevotella*pairwise_interaction_Fusicatenibacter_Prevotella+beta__Fusicatenibacter_Fusicatenibacter*pairwise_interaction_Fusicatenibacter_Fusicatenibacter+beta__Fusicatenibacter_Anaerostipes*pairwise_interaction_Fusicatenibacter_Anaerostipes+beta__Fusicatenibacter_Coprococcus*pairwise_interaction_Fusicatenibacter_Coprococcus+beta__Fusicatenibacter_Akkermansia*pairwise_interaction_Fusicatenibacter_Akkermansia+beta__Fusicatenibacter_Ruminococcus*pairwise_interaction_Fusicatenibacter_Ruminococcus+beta__Fusicatenibacter_Collinsella*pairwise_interaction_Fusicatenibacter_Collinsella+beta__Fusicatenibacter_Gemmiger*pairwise_interaction_Fusicatenibacter_Gemmiger+beta__Fusicatenibacter_Alistipes*pairwise_interaction_Fusicatenibacter_Alistipes+beta__Fusicatenibacter_Clostridium*pairwise_interaction_Fusicatenibacter_Clostridium+beta__Fusicatenibacter_Holdemanella*pairwise_interaction_Fusicatenibacter_Holdemanella+beta__Fusicatenibacter_Dialister*pairwise_interaction_Fusicatenibacter_Dialister+alpha__Anaerostipes*growth_rate_Anaerostipes+epsilon__Anaerostipes*fiber_response_Anaerostipes+beta__Anaerostipes_Others*pairwise_interaction_Anaerostipes_Others+beta__Anaerostipes_Blautia*pairwise_interaction_Anaerostipes_Blautia+beta__Anaerostipes_Faecalibacterium*pairwise_interaction_Anaerostipes_Faecalibacterium+beta__Anaerostipes_Bifidobacterium*pairwise_interaction_Anaerostipes_Bifidobacterium+beta__Anaerostipes_Dorea*pairwise_interaction_Anaerostipes_Dorea+beta__Anaerostipes_Bacteroides*pairwise_interaction_Anaerostipes_Bacteroides+beta__Anaerostipes_Roseburia*pairwise_interaction_Anaerostipes_Roseburia+beta__Anaerostipes_Eubacterium*pairwise_interaction_Anaerostipes_Eubacterium+beta__Anaerostipes_Prevotella*pairwise_interaction_Anaerostipes_Prevotella+beta__Anaerostipes_Fusicatenibacter*pairwise_interaction_Anaerostipes_Fusicatenibacter+beta__Anaerostipes_Anaerostipes*pairwise_interaction_Anaerostipes_Anaerostipes+beta__Anaerostipes_Coprococcus*pairwise_interaction_Anaerostipes_Coprococcus+beta__Anaerostipes_Akkermansia*pairwise_interaction_Anaerostipes_Akkermansia+beta__Anaerostipes_Ruminococcus*pairwise_interaction_Anaerostipes_Ruminococcus+beta__Anaerostipes_Collinsella*pairwise_interaction_Anaerostipes_Collinsella+beta__Anaerostipes_Gemmiger*pairwise_interaction_Anaerostipes_Gemmiger+beta__Anaerostipes_Alistipes*pairwise_interaction_Anaerostipes_Alistipes+beta__Anaerostipes_Clostridium*pairwise_interaction_Anaerostipes_Clostridium+beta__Anaerostipes_Holdemanella*pairwise_interaction_Anaerostipes_Holdemanella+beta__Anaerostipes_Dialister*pairwise_interaction_Anaerostipes_Dialister+alpha__Coprococcus*growth_rate_Coprococcus+epsilon__Coprococcus*fiber_response_Coprococcus+beta__Coprococcus_Others*pairwise_interaction_Coprococcus_Others+beta__Coprococcus_Blautia*pairwise_interaction_Coprococcus_Blautia+beta__Coprococcus_Faecalibacterium*pairwise_interaction_Coprococcus_Faecalibacterium+beta__Coprococcus_Bifidobacterium*pairwise_interaction_Coprococcus_Bifidobacterium+beta__Coprococcus_Dorea*pairwise_interaction_Coprococcus_Dorea+beta__Coprococcus_Bacteroides*pairwise_interaction_Coprococcus_Bacteroides+beta__Coprococcus_Roseburia*pairwise_interaction_Coprococcus_Roseburia+beta__Coprococcus_Eubacterium*pairwise_interaction_Coprococcus_Eubacterium+beta__Coprococcus_Prevotella*pairwise_interaction_Coprococcus_Prevotella+beta__Coprococcus_Fusicatenibacter*pairwise_interaction_Coprococcus_Fusicatenibacter+beta__Coprococcus_Anaerostipes*pairwise_interaction_Coprococcus_Anaerostipes+beta__Coprococcus_Coprococcus*pairwise_interaction_Coprococcus_Coprococcus+beta__Coprococcus_Akkermansia*pairwise_interaction_Coprococcus_Akkermansia+beta__Coprococcus_Ruminococcus*pairwise_interaction_Coprococcus_Ruminococcus+beta__Coprococcus_Collinsella*pairwise_interaction_Coprococcus_Collinsella+beta__Coprococcus_Gemmiger*pairwise_interaction_Coprococcus_Gemmiger+beta__Coprococcus_Alistipes*pairwise_interaction_Coprococcus_Alistipes+beta__Coprococcus_Clostridium*pairwise_interaction_Coprococcus_Clostridium+beta__Coprococcus_Holdemanella*pairwise_interaction_Coprococcus_Holdemanella+beta__Coprococcus_Dialister*pairwise_interaction_Coprococcus_Dialister+alpha__Akkermansia*growth_rate_Akkermansia+epsilon__Akkermansia*fiber_response_Akkermansia+beta__Akkermansia_Others*pairwise_interaction_Akkermansia_Others+beta__Akkermansia_Blautia*pairwise_interaction_Akkermansia_Blautia+beta__Akkermansia_Faecalibacterium*pairwise_interaction_Akkermansia_Faecalibacterium+beta__Akkermansia_Bifidobacterium*pairwise_interaction_Akkermansia_Bifidobacterium+beta__Akkermansia_Dorea*pairwise_interaction_Akkermansia_Dorea+beta__Akkermansia_Bacteroides*pairwise_interaction_Akkermansia_Bacteroides+beta__Akkermansia_Roseburia*pairwise_interaction_Akkermansia_Roseburia+beta__Akkermansia_Eubacterium*pairwise_interaction_Akkermansia_Eubacterium+beta__Akkermansia_Prevotella*pairwise_interaction_Akkermansia_Prevotella+beta__Akkermansia_Fusicatenibacter*pairwise_interaction_Akkermansia_Fusicatenibacter+beta__Akkermansia_Anaerostipes*pairwise_interaction_Akkermansia_Anaerostipes+beta__Akkermansia_Coprococcus*pairwise_interaction_Akkermansia_Coprococcus+beta__Akkermansia_Akkermansia*pairwise_interaction_Akkermansia_Akkermansia+beta__Akkermansia_Ruminococcus*pairwise_interaction_Akkermansia_Ruminococcus+beta__Akkermansia_Collinsella*pairwise_interaction_Akkermansia_Collinsella+beta__Akkermansia_Gemmiger*pairwise_interaction_Akkermansia_Gemmiger+beta__Akkermansia_Alistipes*pairwise_interaction_Akkermansia_Alistipes+beta__Akkermansia_Clostridium*pairwise_interaction_Akkermansia_Clostridium+beta__Akkermansia_Holdemanella*pairwise_interaction_Akkermansia_Holdemanella+beta__Akkermansia_Dialister*pairwise_interaction_Akkermansia_Dialister+alpha__Ruminococcus*growth_rate_Ruminococcus+epsilon__Ruminococcus*fiber_response_Ruminococcus+beta__Ruminococcus_Others*pairwise_interaction_Ruminococcus_Others+beta__Ruminococcus_Blautia*pairwise_interaction_Ruminococcus_Blautia+beta__Ruminococcus_Faecalibacterium*pairwise_interaction_Ruminococcus_Faecalibacterium+beta__Ruminococcus_Bifidobacterium*pairwise_interaction_Ruminococcus_Bifidobacterium+beta__Ruminococcus_Dorea*pairwise_interaction_Ruminococcus_Dorea+beta__Ruminococcus_Bacteroides*pairwise_interaction_Ruminococcus_Bacteroides+beta__Ruminococcus_Roseburia*pairwise_interaction_Ruminococcus_Roseburia+beta__Ruminococcus_Eubacterium*pairwise_interaction_Ruminococcus_Eubacterium+beta__Ruminococcus_Prevotella*pairwise_interaction_Ruminococcus_Prevotella+beta__Ruminococcus_Fusicatenibacter*pairwise_interaction_Ruminococcus_Fusicatenibacter+beta__Ruminococcus_Anaerostipes*pairwise_interaction_Ruminococcus_Anaerostipes+beta__Ruminococcus_Coprococcus*pairwise_interaction_Ruminococcus_Coprococcus+beta__Ruminococcus_Akkermansia*pairwise_interaction_Ruminococcus_Akkermansia+beta__Ruminococcus_Ruminococcus*pairwise_interaction_Ruminococcus_Ruminococcus+beta__Ruminococcus_Collinsella*pairwise_interaction_Ruminococcus_Collinsella+beta__Ruminococcus_Gemmiger*pairwise_interaction_Ruminococcus_Gemmiger+beta__Ruminococcus_Alistipes*pairwise_interaction_Ruminococcus_Alistipes+beta__Ruminococcus_Clostridium*pairwise_interaction_Ruminococcus_Clostridium+beta__Ruminococcus_Holdemanella*pairwise_interaction_Ruminococcus_Holdemanella+beta__Ruminococcus_Dialister*pairwise_interaction_Ruminococcus_Dialister+alpha__Collinsella*growth_rate_Collinsella+epsilon__Collinsella*fiber_response_Collinsella+beta__Collinsella_Others*pairwise_interaction_Collinsella_Others+beta__Collinsella_Blautia*pairwise_interaction_Collinsella_Blautia+beta__Collinsella_Faecalibacterium*pairwise_interaction_Collinsella_Faecalibacterium+beta__Collinsella_Bifidobacterium*pairwise_interaction_Collinsella_Bifidobacterium+beta__Collinsella_Dorea*pairwise_interaction_Collinsella_Dorea+beta__Collinsella_Bacteroides*pairwise_interaction_Collinsella_Bacteroides+beta__Collinsella_Roseburia*pairwise_interaction_Collinsella_Roseburia+beta__Collinsella_Eubacterium*pairwise_interaction_Collinsella_Eubacterium+beta__Collinsella_Prevotella*pairwise_interaction_Collinsella_Prevotella+beta__Collinsella_Fusicatenibacter*pairwise_interaction_Collinsella_Fusicatenibacter+beta__Collinsella_Anaerostipes*pairwise_interaction_Collinsella_Anaerostipes+beta__Collinsella_Coprococcus*pairwise_interaction_Collinsella_Coprococcus+beta__Collinsella_Akkermansia*pairwise_interaction_Collinsella_Akkermansia+beta__Collinsella_Ruminococcus*pairwise_interaction_Collinsella_Ruminococcus+beta__Collinsella_Collinsella*pairwise_interaction_Collinsella_Collinsella+beta__Collinsella_Gemmiger*pairwise_interaction_Collinsella_Gemmiger+beta__Collinsella_Alistipes*pairwise_interaction_Collinsella_Alistipes+beta__Collinsella_Clostridium*pairwise_interaction_Collinsella_Clostridium+beta__Collinsella_Holdemanella*pairwise_interaction_Collinsella_Holdemanella+beta__Collinsella_Dialister*pairwise_interaction_Collinsella_Dialister+alpha__Gemmiger*growth_rate_Gemmiger+epsilon__Gemmiger*fiber_response_Gemmiger+beta__Gemmiger_Others*pairwise_interaction_Gemmiger_Others+beta__Gemmiger_Blautia*pairwise_interaction_Gemmiger_Blautia+beta__Gemmiger_Faecalibacterium*pairwise_interaction_Gemmiger_Faecalibacterium+beta__Gemmiger_Bifidobacterium*pairwise_interaction_Gemmiger_Bifidobacterium+beta__Gemmiger_Dorea*pairwise_interaction_Gemmiger_Dorea+beta__Gemmiger_Bacteroides*pairwise_interaction_Gemmiger_Bacteroides+beta__Gemmiger_Roseburia*pairwise_interaction_Gemmiger_Roseburia+beta__Gemmiger_Eubacterium*pairwise_interaction_Gemmiger_Eubacterium+beta__Gemmiger_Prevotella*pairwise_interaction_Gemmiger_Prevotella+beta__Gemmiger_Fusicatenibacter*pairwise_interaction_Gemmiger_Fusicatenibacter+beta__Gemmiger_Anaerostipes*pairwise_interaction_Gemmiger_Anaerostipes+beta__Gemmiger_Coprococcus*pairwise_interaction_Gemmiger_Coprococcus+beta__Gemmiger_Akkermansia*pairwise_interaction_Gemmiger_Akkermansia+beta__Gemmiger_Ruminococcus*pairwise_interaction_Gemmiger_Ruminococcus+beta__Gemmiger_Collinsella*pairwise_interaction_Gemmiger_Collinsella+beta__Gemmiger_Gemmiger*pairwise_interaction_Gemmiger_Gemmiger+beta__Gemmiger_Alistipes*pairwise_interaction_Gemmiger_Alistipes+beta__Gemmiger_Clostridium*pairwise_interaction_Gemmiger_Clostridium+beta__Gemmiger_Holdemanella*pairwise_interaction_Gemmiger_Holdemanella+beta__Gemmiger_Dialister*pairwise_interaction_Gemmiger_Dialister+alpha__Alistipes*growth_rate_Alistipes+epsilon__Alistipes*fiber_response_Alistipes+beta__Alistipes_Others*pairwise_interaction_Alistipes_Others+beta__Alistipes_Blautia*pairwise_interaction_Alistipes_Blautia+beta__Alistipes_Faecalibacterium*pairwise_interaction_Alistipes_Faecalibacterium+beta__Alistipes_Bifidobacterium*pairwise_interaction_Alistipes_Bifidobacterium+beta__Alistipes_Dorea*pairwise_interaction_Alistipes_Dorea+beta__Alistipes_Bacteroides*pairwise_interaction_Alistipes_Bacteroides+beta__Alistipes_Roseburia*pairwise_interaction_Alistipes_Roseburia+beta__Alistipes_Eubacterium*pairwise_interaction_Alistipes_Eubacterium+beta__Alistipes_Prevotella*pairwise_interaction_Alistipes_Prevotella+beta__Alistipes_Fusicatenibacter*pairwise_interaction_Alistipes_Fusicatenibacter+beta__Alistipes_Anaerostipes*pairwise_interaction_Alistipes_Anaerostipes+beta__Alistipes_Coprococcus*pairwise_interaction_Alistipes_Coprococcus+beta__Alistipes_Akkermansia*pairwise_interaction_Alistipes_Akkermansia+beta__Alistipes_Ruminococcus*pairwise_interaction_Alistipes_Ruminococcus+beta__Alistipes_Collinsella*pairwise_interaction_Alistipes_Collinsella+beta__Alistipes_Gemmiger*pairwise_interaction_Alistipes_Gemmiger+beta__Alistipes_Alistipes*pairwise_interaction_Alistipes_Alistipes+beta__Alistipes_Clostridium*pairwise_interaction_Alistipes_Clostridium+beta__Alistipes_Holdemanella*pairwise_interaction_Alistipes_Holdemanella+beta__Alistipes_Dialister*pairwise_interaction_Alistipes_Dialister+alpha__Clostridium*growth_rate_Clostridium+epsilon__Clostridium*fiber_response_Clostridium+beta__Clostridium_Others*pairwise_interaction_Clostridium_Others+beta__Clostridium_Blautia*pairwise_interaction_Clostridium_Blautia+beta__Clostridium_Faecalibacterium*pairwise_interaction_Clostridium_Faecalibacterium+beta__Clostridium_Bifidobacterium*pairwise_interaction_Clostridium_Bifidobacterium+beta__Clostridium_Dorea*pairwise_interaction_Clostridium_Dorea+beta__Clostridium_Bacteroides*pairwise_interaction_Clostridium_Bacteroides+beta__Clostridium_Roseburia*pairwise_interaction_Clostridium_Roseburia+beta__Clostridium_Eubacterium*pairwise_interaction_Clostridium_Eubacterium+beta__Clostridium_Prevotella*pairwise_interaction_Clostridium_Prevotella+beta__Clostridium_Fusicatenibacter*pairwise_interaction_Clostridium_Fusicatenibacter+beta__Clostridium_Anaerostipes*pairwise_interaction_Clostridium_Anaerostipes+beta__Clostridium_Coprococcus*pairwise_interaction_Clostridium_Coprococcus+beta__Clostridium_Akkermansia*pairwise_interaction_Clostridium_Akkermansia+beta__Clostridium_Ruminococcus*pairwise_interaction_Clostridium_Ruminococcus+beta__Clostridium_Collinsella*pairwise_interaction_Clostridium_Collinsella+beta__Clostridium_Gemmiger*pairwise_interaction_Clostridium_Gemmiger+beta__Clostridium_Alistipes*pairwise_interaction_Clostridium_Alistipes+beta__Clostridium_Clostridium*pairwise_interaction_Clostridium_Clostridium+beta__Clostridium_Holdemanella*pairwise_interaction_Clostridium_Holdemanella+beta__Clostridium_Dialister*pairwise_interaction_Clostridium_Dialister+alpha__Holdemanella*growth_rate_Holdemanella+epsilon__Holdemanella*fiber_response_Holdemanella+beta__Holdemanella_Others*pairwise_interaction_Holdemanella_Others+beta__Holdemanella_Blautia*pairwise_interaction_Holdemanella_Blautia+beta__Holdemanella_Faecalibacterium*pairwise_interaction_Holdemanella_Faecalibacterium+beta__Holdemanella_Bifidobacterium*pairwise_interaction_Holdemanella_Bifidobacterium+beta__Holdemanella_Dorea*pairwise_interaction_Holdemanella_Dorea+beta__Holdemanella_Bacteroides*pairwise_interaction_Holdemanella_Bacteroides+beta__Holdemanella_Roseburia*pairwise_interaction_Holdemanella_Roseburia+beta__Holdemanella_Eubacterium*pairwise_interaction_Holdemanella_Eubacterium+beta__Holdemanella_Prevotella*pairwise_interaction_Holdemanella_Prevotella+beta__Holdemanella_Fusicatenibacter*pairwise_interaction_Holdemanella_Fusicatenibacter+beta__Holdemanella_Anaerostipes*pairwise_interaction_Holdemanella_Anaerostipes+beta__Holdemanella_Coprococcus*pairwise_interaction_Holdemanella_Coprococcus+beta__Holdemanella_Akkermansia*pairwise_interaction_Holdemanella_Akkermansia+beta__Holdemanella_Ruminococcus*pairwise_interaction_Holdemanella_Ruminococcus+beta__Holdemanella_Collinsella*pairwise_interaction_Holdemanella_Collinsella+beta__Holdemanella_Gemmiger*pairwise_interaction_Holdemanella_Gemmiger+beta__Holdemanella_Alistipes*pairwise_interaction_Holdemanella_Alistipes+beta__Holdemanella_Clostridium*pairwise_interaction_Holdemanella_Clostridium+beta__Holdemanella_Holdemanella*pairwise_interaction_Holdemanella_Holdemanella+beta__Holdemanella_Dialister*pairwise_interaction_Holdemanella_Dialister+alpha__Dialister*growth_rate_Dialister+epsilon__Dialister*fiber_response_Dialister+beta__Dialister_Others*pairwise_interaction_Dialister_Others+beta__Dialister_Blautia*pairwise_interaction_Dialister_Blautia+beta__Dialister_Faecalibacterium*pairwise_interaction_Dialister_Faecalibacterium+beta__Dialister_Bifidobacterium*pairwise_interaction_Dialister_Bifidobacterium+beta__Dialister_Dorea*pairwise_interaction_Dialister_Dorea+beta__Dialister_Bacteroides*pairwise_interaction_Dialister_Bacteroides+beta__Dialister_Roseburia*pairwise_interaction_Dialister_Roseburia+beta__Dialister_Eubacterium*pairwise_interaction_Dialister_Eubacterium+beta__Dialister_Prevotella*pairwise_interaction_Dialister_Prevotella+beta__Dialister_Fusicatenibacter*pairwise_interaction_Dialister_Fusicatenibacter+beta__Dialister_Anaerostipes*pairwise_interaction_Dialister_Anaerostipes+beta__Dialister_Coprococcus*pairwise_interaction_Dialister_Coprococcus+beta__Dialister_Akkermansia*pairwise_interaction_Dialister_Akkermansia+beta__Dialister_Ruminococcus*pairwise_interaction_Dialister_Ruminococcus+beta__Dialister_Collinsella*pairwise_interaction_Dialister_Collinsella+beta__Dialister_Gemmiger*pairwise_interaction_Dialister_Gemmiger+beta__Dialister_Alistipes*pairwise_interaction_Dialister_Alistipes+beta__Dialister_Clostridium*pairwise_interaction_Dialister_Clostridium+beta__Dialister_Holdemanella*pairwise_interaction_Dialister_Holdemanella+beta__Dialister_Dialister*pairwise_interaction_Dialister_Dialister, sigma);
}